#pragma once

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C"
{
#endif // __cplusplus

#if defined(_WIN32)
#  define VKAPI_CALL __stdcall
#  define VKAPI_PTR  VKAPI_CALL
#else
#  define VKAPI_CALL
#  define VKAPI_PTR
#endif

#define VK_MAKE_VERSION(major, minor, patch) \
    (((major) << 22) | ((minor) << 12) | (patch))
#define VK_API_VERSION_1_0 VK_MAKE_VERSION(1, 0, 0)
#define VK_API_VERSION_1_1 VK_MAKE_VERSION(1, 1, 0)

#define VK_DEFINE_HANDLE(object) typedef struct object##_T* object;
#if !defined(VK_DEFINE_NON_DISPATCHABLE_HANDLE)
#if defined(__LP64__) || defined(_WIN64) || (defined(__x86_64__) && !defined(__ILP32__) ) || defined(_M_X64) || defined(__ia64) || defined (_M_IA64) || defined(__aarch64__) || defined(__powerpc64__)
#define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef struct object##_T *object;
#else
#define VK_DEFINE_NON_DISPATCHABLE_HANDLE(object) typedef uint64_t object;
#endif
#endif

#define VK_FALSE 0
#define VK_TRUE 1
#define VK_MAX_PHYSICAL_DEVICE_NAME_SIZE  256
#define VK_UUID_SIZE                      16
#define VK_NULL_HANDLE 0

typedef uint32_t VkFlags;
typedef uint32_t VkBool32;
typedef uint64_t VkDeviceSize;
typedef uint32_t VkSampleMask;
typedef void (VKAPI_PTR *PFN_vkVoidFunction)(void);

VK_DEFINE_HANDLE(VkInstance);
VK_DEFINE_HANDLE(VkPhysicalDevice);
VK_DEFINE_HANDLE(VkDevice);
VK_DEFINE_HANDLE(VkQueue);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkSemaphore);
VK_DEFINE_HANDLE(VkCommandBuffer);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkFence);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkDeviceMemory);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkBuffer);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkImage);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkEvent);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkQueryPool);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkBufferView);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkImageView);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkShaderModule);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkPipelineCache);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkPipelineLayout);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkRenderPass);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkPipeline);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkDescriptorSetLayout);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkSampler);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkDescriptorPool);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkDescriptorSet);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkFramebuffer);
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkCommandPool);

#define VK_KHR_surface 1
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkSurfaceKHR)
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkSwapchainKHR)

typedef enum VkResult {
   VK_SUCCESS = 0,
   VK_NOT_READY = 1,
   VK_TIMEOUT = 2,
   VK_EVENT_SET = 3,
   VK_EVENT_RESET = 4,
   VK_INCOMPLETE = 5,
   VK_ERROR_OUT_OF_HOST_MEMORY = -1,
   VK_ERROR_OUT_OF_DEVICE_MEMORY = -2,
   VK_ERROR_INITIALIZATION_FAILED = -3,
   VK_ERROR_DEVICE_LOST = -4,
   VK_ERROR_MEMORY_MAP_FAILED = -5,
   VK_ERROR_LAYER_NOT_PRESENT = -6,
   VK_ERROR_EXTENSION_NOT_PRESENT = -7,
   VK_ERROR_FEATURE_NOT_PRESENT = -8,
   VK_ERROR_INCOMPATIBLE_DRIVER = -9,
   VK_ERROR_TOO_MANY_OBJECTS = -10,
   VK_ERROR_FORMAT_NOT_SUPPORTED = -11,
   VK_ERROR_FRAGMENTED_POOL = -12,
   VK_ERROR_OUT_OF_POOL_MEMORY = -1000069000,
   VK_ERROR_INVALID_EXTERNAL_HANDLE = -1000072003,
   VK_ERROR_SURFACE_LOST_KHR = -1000000000,
   VK_ERROR_NATIVE_WINDOW_IN_USE_KHR = -1000000001,
   VK_SUBOPTIMAL_KHR = 1000001003,
   VK_ERROR_OUT_OF_DATE_KHR = -1000001004,
   VK_ERROR_INCOMPATIBLE_DISPLAY_KHR = -1000003001,
   VK_ERROR_VALIDATION_FAILED_EXT = -1000011001,
   VK_ERROR_INVALID_SHADER_NV = -1000012000,
   VK_ERROR_FRAGMENTATION_EXT = -1000161000,
   VK_ERROR_NOT_PERMITTED_EXT = -1000174001,
   VK_ERROR_OUT_OF_POOL_MEMORY_KHR = VK_ERROR_OUT_OF_POOL_MEMORY,
   VK_ERROR_INVALID_EXTERNAL_HANDLE_KHR = VK_ERROR_INVALID_EXTERNAL_HANDLE,
   VK_RESULT_BEGIN_RANGE = VK_ERROR_FRAGMENTED_POOL,
   VK_RESULT_END_RANGE = VK_INCOMPLETE,
   VK_RESULT_RANGE_SIZE = (VK_INCOMPLETE - VK_ERROR_FRAGMENTED_POOL + 1),
   VK_RESULT_MAX_ENUM = 0x7FFFFFFF
} VkResult;

typedef enum VkStructureType {
   VK_STRUCTURE_TYPE_APPLICATION_INFO = 0,
   VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO = 1,
   VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO = 2,
   VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO = 3,
   VK_STRUCTURE_TYPE_SUBMIT_INFO = 4,
   VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO = 5,
   VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE = 6,
   VK_STRUCTURE_TYPE_BIND_SPARSE_INFO = 7,
   VK_STRUCTURE_TYPE_FENCE_CREATE_INFO = 8,
   VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO = 9,
   VK_STRUCTURE_TYPE_EVENT_CREATE_INFO = 10,
   VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO = 11,
   VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO = 12,
   VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO = 13,
   VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO = 14,
   VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO = 15,
   VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO = 16,
   VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO = 17,
   VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO = 18,
   VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO = 19,
   VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO = 20,
   VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO = 21,
   VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO = 22,
   VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO = 23,
   VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO = 24,
   VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO = 25,
   VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO = 26,
   VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO = 27,
   VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO = 28,
   VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO = 29,
   VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO = 30,
   VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO = 31,
   VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO = 32,
   VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO = 33,
   VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO = 34,
   VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET = 35,
   VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET = 36,
   VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO = 37,
   VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO = 38,
   VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO = 39,
   VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO = 40,
   VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO = 41,
   VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO = 42,
   VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO = 43,
   VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER = 44,
   VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER = 45,
   VK_STRUCTURE_TYPE_MEMORY_BARRIER = 46,
   VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO = 47,
   VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO = 48,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SUBGROUP_PROPERTIES = 1000094000,
   VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO = 1000157000,
   VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO = 1000157001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES = 1000083000,
   VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS = 1000127000,
   VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO = 1000127001,
   VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO = 1000060000,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO = 1000060003,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO = 1000060004,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO = 1000060005,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO = 1000060006,
   VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO = 1000060013,
   VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO = 1000060014,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES = 1000070000,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO = 1000070001,
   VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2 = 1000146000,
   VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2 = 1000146001,
   VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2 = 1000146002,
   VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2 = 1000146003,
   VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2 = 1000146004,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2 = 1000059000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2 = 1000059001,
   VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2 = 1000059002,
   VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2 = 1000059003,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2 = 1000059004,
   VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2 = 1000059005,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2 = 1000059006,
   VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2 = 1000059007,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2 = 1000059008,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES = 1000117000,
   VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO = 1000117001,
   VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO = 1000117002,
   VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO = 1000117003,
   VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO = 1000053000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES = 1000053001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES = 1000053002,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES = 1000120000,
   VK_STRUCTURE_TYPE_PROTECTED_SUBMIT_INFO = 1000145000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_FEATURES = 1000145001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROTECTED_MEMORY_PROPERTIES = 1000145002,
   VK_STRUCTURE_TYPE_DEVICE_QUEUE_INFO_2 = 1000145003,
   VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO = 1000156000,
   VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO = 1000156001,
   VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO = 1000156002,
   VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO = 1000156003,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES = 1000156004,
   VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES = 1000156005,
   VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO = 1000085000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO = 1000071000,
   VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES = 1000071001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO = 1000071002,
   VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES = 1000071003,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES = 1000071004,
   VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO = 1000072000,
   VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO = 1000072001,
   VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO = 1000072002,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO = 1000112000,
   VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES = 1000112001,
   VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO = 1000113000,
   VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO = 1000077000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO = 1000076000,
   VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES = 1000076001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES = 1000168000,
   VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT = 1000168001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_DRAW_PARAMETER_FEATURES = 1000063000,
   VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR = 1000001000,
   VK_STRUCTURE_TYPE_PRESENT_INFO_KHR = 1000001001,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_CAPABILITIES_KHR = 1000060007,
   VK_STRUCTURE_TYPE_IMAGE_SWAPCHAIN_CREATE_INFO_KHR = 1000060008,
   VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_SWAPCHAIN_INFO_KHR = 1000060009,
   VK_STRUCTURE_TYPE_ACQUIRE_NEXT_IMAGE_INFO_KHR = 1000060010,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_INFO_KHR = 1000060011,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_SWAPCHAIN_CREATE_INFO_KHR = 1000060012,
   VK_STRUCTURE_TYPE_DISPLAY_MODE_CREATE_INFO_KHR = 1000002000,
   VK_STRUCTURE_TYPE_DISPLAY_SURFACE_CREATE_INFO_KHR = 1000002001,
   VK_STRUCTURE_TYPE_DISPLAY_PRESENT_INFO_KHR = 1000003000,
   VK_STRUCTURE_TYPE_XLIB_SURFACE_CREATE_INFO_KHR = 1000004000,
   VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR = 1000005000,
   VK_STRUCTURE_TYPE_WAYLAND_SURFACE_CREATE_INFO_KHR = 1000006000,
   VK_STRUCTURE_TYPE_MIR_SURFACE_CREATE_INFO_KHR = 1000007000,
   VK_STRUCTURE_TYPE_ANDROID_SURFACE_CREATE_INFO_KHR = 1000008000,
   VK_STRUCTURE_TYPE_WIN32_SURFACE_CREATE_INFO_KHR = 1000009000,
   VK_STRUCTURE_TYPE_DEBUG_REPORT_CALLBACK_CREATE_INFO_EXT = 1000011000,
   VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_RASTERIZATION_ORDER_AMD = 1000018000,
   VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_NAME_INFO_EXT = 1000022000,
   VK_STRUCTURE_TYPE_DEBUG_MARKER_OBJECT_TAG_INFO_EXT = 1000022001,
   VK_STRUCTURE_TYPE_DEBUG_MARKER_MARKER_INFO_EXT = 1000022002,
   VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_IMAGE_CREATE_INFO_NV = 1000026000,
   VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_BUFFER_CREATE_INFO_NV = 1000026001,
   VK_STRUCTURE_TYPE_DEDICATED_ALLOCATION_MEMORY_ALLOCATE_INFO_NV = 1000026002,
   VK_STRUCTURE_TYPE_TEXTURE_LOD_GATHER_FORMAT_PROPERTIES_AMD = 1000041000,
   VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO_NV = 1000056000,
   VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO_NV = 1000056001,
   VK_STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_NV = 1000057000,
   VK_STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_NV = 1000057001,
   VK_STRUCTURE_TYPE_WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_NV = 1000058000,
   VK_STRUCTURE_TYPE_VALIDATION_FLAGS_EXT = 1000061000,
   VK_STRUCTURE_TYPE_VI_SURFACE_CREATE_INFO_NN = 1000062000,
   VK_STRUCTURE_TYPE_IMPORT_MEMORY_WIN32_HANDLE_INFO_KHR = 1000073000,
   VK_STRUCTURE_TYPE_EXPORT_MEMORY_WIN32_HANDLE_INFO_KHR = 1000073001,
   VK_STRUCTURE_TYPE_MEMORY_WIN32_HANDLE_PROPERTIES_KHR = 1000073002,
   VK_STRUCTURE_TYPE_MEMORY_GET_WIN32_HANDLE_INFO_KHR = 1000073003,
   VK_STRUCTURE_TYPE_IMPORT_MEMORY_FD_INFO_KHR = 1000074000,
   VK_STRUCTURE_TYPE_MEMORY_FD_PROPERTIES_KHR = 1000074001,
   VK_STRUCTURE_TYPE_MEMORY_GET_FD_INFO_KHR = 1000074002,
   VK_STRUCTURE_TYPE_WIN32_KEYED_MUTEX_ACQUIRE_RELEASE_INFO_KHR = 1000075000,
   VK_STRUCTURE_TYPE_IMPORT_SEMAPHORE_WIN32_HANDLE_INFO_KHR = 1000078000,
   VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_WIN32_HANDLE_INFO_KHR = 1000078001,
   VK_STRUCTURE_TYPE_D3D12_FENCE_SUBMIT_INFO_KHR = 1000078002,
   VK_STRUCTURE_TYPE_SEMAPHORE_GET_WIN32_HANDLE_INFO_KHR = 1000078003,
   VK_STRUCTURE_TYPE_IMPORT_SEMAPHORE_FD_INFO_KHR = 1000079000,
   VK_STRUCTURE_TYPE_SEMAPHORE_GET_FD_INFO_KHR = 1000079001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PUSH_DESCRIPTOR_PROPERTIES_KHR = 1000080000,
   VK_STRUCTURE_TYPE_PRESENT_REGIONS_KHR = 1000084000,
   VK_STRUCTURE_TYPE_OBJECT_TABLE_CREATE_INFO_NVX = 1000086000,
   VK_STRUCTURE_TYPE_INDIRECT_COMMANDS_LAYOUT_CREATE_INFO_NVX = 1000086001,
   VK_STRUCTURE_TYPE_CMD_PROCESS_COMMANDS_INFO_NVX = 1000086002,
   VK_STRUCTURE_TYPE_CMD_RESERVE_SPACE_FOR_COMMANDS_INFO_NVX = 1000086003,
   VK_STRUCTURE_TYPE_DEVICE_GENERATED_COMMANDS_LIMITS_NVX = 1000086004,
   VK_STRUCTURE_TYPE_DEVICE_GENERATED_COMMANDS_FEATURES_NVX = 1000086005,
   VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_W_SCALING_STATE_CREATE_INFO_NV = 1000087000,
   VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES_2_EXT = 1000090000,
   VK_STRUCTURE_TYPE_DISPLAY_POWER_INFO_EXT = 1000091000,
   VK_STRUCTURE_TYPE_DEVICE_EVENT_INFO_EXT = 1000091001,
   VK_STRUCTURE_TYPE_DISPLAY_EVENT_INFO_EXT = 1000091002,
   VK_STRUCTURE_TYPE_SWAPCHAIN_COUNTER_CREATE_INFO_EXT = 1000091003,
   VK_STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE = 1000092000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PER_VIEW_ATTRIBUTES_PROPERTIES_NVX = 1000097000,
   VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_SWIZZLE_STATE_CREATE_INFO_NV = 1000098000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DISCARD_RECTANGLE_PROPERTIES_EXT = 1000099000,
   VK_STRUCTURE_TYPE_PIPELINE_DISCARD_RECTANGLE_STATE_CREATE_INFO_EXT = 1000099001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_CONSERVATIVE_RASTERIZATION_PROPERTIES_EXT = 1000101000,
   VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_CONSERVATIVE_STATE_CREATE_INFO_EXT = 1000101001,
   VK_STRUCTURE_TYPE_HDR_METADATA_EXT = 1000105000,
   VK_STRUCTURE_TYPE_SHARED_PRESENT_SURFACE_CAPABILITIES_KHR = 1000111000,
   VK_STRUCTURE_TYPE_IMPORT_FENCE_WIN32_HANDLE_INFO_KHR = 1000114000,
   VK_STRUCTURE_TYPE_EXPORT_FENCE_WIN32_HANDLE_INFO_KHR = 1000114001,
   VK_STRUCTURE_TYPE_FENCE_GET_WIN32_HANDLE_INFO_KHR = 1000114002,
   VK_STRUCTURE_TYPE_IMPORT_FENCE_FD_INFO_KHR = 1000115000,
   VK_STRUCTURE_TYPE_FENCE_GET_FD_INFO_KHR = 1000115001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SURFACE_INFO_2_KHR = 1000119000,
   VK_STRUCTURE_TYPE_SURFACE_CAPABILITIES_2_KHR = 1000119001,
   VK_STRUCTURE_TYPE_SURFACE_FORMAT_2_KHR = 1000119002,
   VK_STRUCTURE_TYPE_IOS_SURFACE_CREATE_INFO_MVK = 1000122000,
   VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK = 1000123000,
   VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT = 1000128000,
   VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_TAG_INFO_EXT = 1000128001,
   VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT = 1000128002,
   VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT = 1000128003,
   VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT = 1000128004,
   VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_USAGE_ANDROID = 1000129000,
   VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_PROPERTIES_ANDROID = 1000129001,
   VK_STRUCTURE_TYPE_ANDROID_HARDWARE_BUFFER_FORMAT_PROPERTIES_ANDROID = 1000129002,
   VK_STRUCTURE_TYPE_IMPORT_ANDROID_HARDWARE_BUFFER_INFO_ANDROID = 1000129003,
   VK_STRUCTURE_TYPE_MEMORY_GET_ANDROID_HARDWARE_BUFFER_INFO_ANDROID = 1000129004,
   VK_STRUCTURE_TYPE_EXTERNAL_FORMAT_ANDROID = 1000129005,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_FILTER_MINMAX_PROPERTIES_EXT = 1000130000,
   VK_STRUCTURE_TYPE_SAMPLER_REDUCTION_MODE_CREATE_INFO_EXT = 1000130001,
   VK_STRUCTURE_TYPE_SAMPLE_LOCATIONS_INFO_EXT = 1000143000,
   VK_STRUCTURE_TYPE_RENDER_PASS_SAMPLE_LOCATIONS_BEGIN_INFO_EXT = 1000143001,
   VK_STRUCTURE_TYPE_PIPELINE_SAMPLE_LOCATIONS_STATE_CREATE_INFO_EXT = 1000143002,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLE_LOCATIONS_PROPERTIES_EXT = 1000143003,
   VK_STRUCTURE_TYPE_MULTISAMPLE_PROPERTIES_EXT = 1000143004,
   VK_STRUCTURE_TYPE_IMAGE_FORMAT_LIST_CREATE_INFO_KHR = 1000147000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_FEATURES_EXT = 1000148000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_BLEND_OPERATION_ADVANCED_PROPERTIES_EXT = 1000148001,
   VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_ADVANCED_STATE_CREATE_INFO_EXT = 1000148002,
   VK_STRUCTURE_TYPE_PIPELINE_COVERAGE_TO_COLOR_STATE_CREATE_INFO_NV = 1000149000,
   VK_STRUCTURE_TYPE_PIPELINE_COVERAGE_MODULATION_STATE_CREATE_INFO_NV = 1000152000,
   VK_STRUCTURE_TYPE_VALIDATION_CACHE_CREATE_INFO_EXT = 1000160000,
   VK_STRUCTURE_TYPE_SHADER_MODULE_VALIDATION_CACHE_CREATE_INFO_EXT = 1000160001,
   VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_BINDING_FLAGS_CREATE_INFO_EXT = 1000161000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_FEATURES_EXT = 1000161001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_DESCRIPTOR_INDEXING_PROPERTIES_EXT = 1000161002,
   VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_ALLOCATE_INFO_EXT = 1000161003,
   VK_STRUCTURE_TYPE_DESCRIPTOR_SET_VARIABLE_DESCRIPTOR_COUNT_LAYOUT_SUPPORT_EXT = 1000161004,
   VK_STRUCTURE_TYPE_DEVICE_QUEUE_GLOBAL_PRIORITY_CREATE_INFO_EXT = 1000174000,
   VK_STRUCTURE_TYPE_IMPORT_MEMORY_HOST_POINTER_INFO_EXT = 1000178000,
   VK_STRUCTURE_TYPE_MEMORY_HOST_POINTER_PROPERTIES_EXT = 1000178001,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_MEMORY_HOST_PROPERTIES_EXT = 1000178002,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SHADER_CORE_PROPERTIES_AMD = 1000185000,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VERTEX_ATTRIBUTE_DIVISOR_PROPERTIES_EXT = 1000190000,
   VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_DIVISOR_STATE_CREATE_INFO_EXT = 1000190001,
   VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_RENDER_PASS_MULTIVIEW_CREATE_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_FEATURES,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MULTIVIEW_PROPERTIES,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_PROPERTIES_2,
   VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2_KHR = VK_STRUCTURE_TYPE_FORMAT_PROPERTIES_2,
   VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2_KHR = VK_STRUCTURE_TYPE_IMAGE_FORMAT_PROPERTIES_2,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_IMAGE_FORMAT_INFO_2,
   VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2_KHR = VK_STRUCTURE_TYPE_QUEUE_FAMILY_PROPERTIES_2,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MEMORY_PROPERTIES_2,
   VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2_KHR = VK_STRUCTURE_TYPE_SPARSE_IMAGE_FORMAT_PROPERTIES_2,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SPARSE_IMAGE_FORMAT_INFO_2,
   VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO_KHR = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_FLAGS_INFO,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO_KHR = VK_STRUCTURE_TYPE_DEVICE_GROUP_RENDER_PASS_BEGIN_INFO,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO_KHR = VK_STRUCTURE_TYPE_DEVICE_GROUP_COMMAND_BUFFER_BEGIN_INFO,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO_KHR = VK_STRUCTURE_TYPE_DEVICE_GROUP_SUBMIT_INFO,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO_KHR = VK_STRUCTURE_TYPE_DEVICE_GROUP_BIND_SPARSE_INFO,
   VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO_KHR = VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_DEVICE_GROUP_INFO,
   VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO_KHR = VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_DEVICE_GROUP_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_GROUP_PROPERTIES,
   VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_DEVICE_GROUP_DEVICE_CREATE_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_IMAGE_FORMAT_INFO,
   VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES_KHR = VK_STRUCTURE_TYPE_EXTERNAL_IMAGE_FORMAT_PROPERTIES,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_BUFFER_INFO,
   VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES_KHR = VK_STRUCTURE_TYPE_EXTERNAL_BUFFER_PROPERTIES,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_ID_PROPERTIES,
   VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_BUFFER_CREATE_INFO,
   VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_EXTERNAL_MEMORY_IMAGE_CREATE_INFO,
   VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO_KHR = VK_STRUCTURE_TYPE_EXPORT_MEMORY_ALLOCATE_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_SEMAPHORE_INFO,
   VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES_KHR = VK_STRUCTURE_TYPE_EXTERNAL_SEMAPHORE_PROPERTIES,
   VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_EXPORT_SEMAPHORE_CREATE_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_16BIT_STORAGE_FEATURES,
   VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_CREATE_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_EXTERNAL_FENCE_INFO,
   VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES_KHR = VK_STRUCTURE_TYPE_EXTERNAL_FENCE_PROPERTIES,
   VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_EXPORT_FENCE_CREATE_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_POINT_CLIPPING_PROPERTIES,
   VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_RENDER_PASS_INPUT_ATTACHMENT_ASPECT_CREATE_INFO,
   VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_IMAGE_VIEW_USAGE_CREATE_INFO,
   VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_DOMAIN_ORIGIN_STATE_CREATE_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VARIABLE_POINTER_FEATURES,
   VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS_KHR = VK_STRUCTURE_TYPE_MEMORY_DEDICATED_REQUIREMENTS,
   VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO_KHR = VK_STRUCTURE_TYPE_MEMORY_DEDICATED_ALLOCATE_INFO,
   VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2_KHR = VK_STRUCTURE_TYPE_BUFFER_MEMORY_REQUIREMENTS_INFO_2,
   VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2_KHR = VK_STRUCTURE_TYPE_IMAGE_MEMORY_REQUIREMENTS_INFO_2,
   VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2_KHR = VK_STRUCTURE_TYPE_IMAGE_SPARSE_MEMORY_REQUIREMENTS_INFO_2,
   VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2_KHR = VK_STRUCTURE_TYPE_MEMORY_REQUIREMENTS_2,
   VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2_KHR = VK_STRUCTURE_TYPE_SPARSE_IMAGE_MEMORY_REQUIREMENTS_2,
   VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO_KHR = VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_CREATE_INFO,
   VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO_KHR = VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_INFO,
   VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO_KHR = VK_STRUCTURE_TYPE_BIND_IMAGE_PLANE_MEMORY_INFO,
   VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO_KHR = VK_STRUCTURE_TYPE_IMAGE_PLANE_MEMORY_REQUIREMENTS_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SAMPLER_YCBCR_CONVERSION_FEATURES,
   VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES_KHR = VK_STRUCTURE_TYPE_SAMPLER_YCBCR_CONVERSION_IMAGE_FORMAT_PROPERTIES,
   VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO_KHR = VK_STRUCTURE_TYPE_BIND_BUFFER_MEMORY_INFO,
   VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO_KHR = VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_INFO,
   VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES_KHR = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_MAINTENANCE_3_PROPERTIES,
   VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT_KHR = VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_SUPPORT,
   VK_STRUCTURE_TYPE_BEGIN_RANGE = VK_STRUCTURE_TYPE_APPLICATION_INFO,
   VK_STRUCTURE_TYPE_END_RANGE = VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO,
   VK_STRUCTURE_TYPE_RANGE_SIZE = (VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO - VK_STRUCTURE_TYPE_APPLICATION_INFO + 1),
   VK_STRUCTURE_TYPE_MAX_ENUM = 0x7FFFFFFF
} VkStructureType;

typedef enum VkFormat {
   VK_FORMAT_UNDEFINED = 0,
   VK_FORMAT_R4G4_UNORM_PACK8 = 1,
   VK_FORMAT_R4G4B4A4_UNORM_PACK16 = 2,
   VK_FORMAT_B4G4R4A4_UNORM_PACK16 = 3,
   VK_FORMAT_R5G6B5_UNORM_PACK16 = 4,
   VK_FORMAT_B5G6R5_UNORM_PACK16 = 5,
   VK_FORMAT_R5G5B5A1_UNORM_PACK16 = 6,
   VK_FORMAT_B5G5R5A1_UNORM_PACK16 = 7,
   VK_FORMAT_A1R5G5B5_UNORM_PACK16 = 8,
   VK_FORMAT_R8_UNORM = 9,
   VK_FORMAT_R8_SNORM = 10,
   VK_FORMAT_R8_USCALED = 11,
   VK_FORMAT_R8_SSCALED = 12,
   VK_FORMAT_R8_UINT = 13,
   VK_FORMAT_R8_SINT = 14,
   VK_FORMAT_R8_SRGB = 15,
   VK_FORMAT_R8G8_UNORM = 16,
   VK_FORMAT_R8G8_SNORM = 17,
   VK_FORMAT_R8G8_USCALED = 18,
   VK_FORMAT_R8G8_SSCALED = 19,
   VK_FORMAT_R8G8_UINT = 20,
   VK_FORMAT_R8G8_SINT = 21,
   VK_FORMAT_R8G8_SRGB = 22,
   VK_FORMAT_R8G8B8_UNORM = 23,
   VK_FORMAT_R8G8B8_SNORM = 24,
   VK_FORMAT_R8G8B8_USCALED = 25,
   VK_FORMAT_R8G8B8_SSCALED = 26,
   VK_FORMAT_R8G8B8_UINT = 27,
   VK_FORMAT_R8G8B8_SINT = 28,
   VK_FORMAT_R8G8B8_SRGB = 29,
   VK_FORMAT_B8G8R8_UNORM = 30,
   VK_FORMAT_B8G8R8_SNORM = 31,
   VK_FORMAT_B8G8R8_USCALED = 32,
   VK_FORMAT_B8G8R8_SSCALED = 33,
   VK_FORMAT_B8G8R8_UINT = 34,
   VK_FORMAT_B8G8R8_SINT = 35,
   VK_FORMAT_B8G8R8_SRGB = 36,
   VK_FORMAT_R8G8B8A8_UNORM = 37,
   VK_FORMAT_R8G8B8A8_SNORM = 38,
   VK_FORMAT_R8G8B8A8_USCALED = 39,
   VK_FORMAT_R8G8B8A8_SSCALED = 40,
   VK_FORMAT_R8G8B8A8_UINT = 41,
   VK_FORMAT_R8G8B8A8_SINT = 42,
   VK_FORMAT_R8G8B8A8_SRGB = 43,
   VK_FORMAT_B8G8R8A8_UNORM = 44,
   VK_FORMAT_B8G8R8A8_SNORM = 45,
   VK_FORMAT_B8G8R8A8_USCALED = 46,
   VK_FORMAT_B8G8R8A8_SSCALED = 47,
   VK_FORMAT_B8G8R8A8_UINT = 48,
   VK_FORMAT_B8G8R8A8_SINT = 49,
   VK_FORMAT_B8G8R8A8_SRGB = 50,
   VK_FORMAT_A8B8G8R8_UNORM_PACK32 = 51,
   VK_FORMAT_A8B8G8R8_SNORM_PACK32 = 52,
   VK_FORMAT_A8B8G8R8_USCALED_PACK32 = 53,
   VK_FORMAT_A8B8G8R8_SSCALED_PACK32 = 54,
   VK_FORMAT_A8B8G8R8_UINT_PACK32 = 55,
   VK_FORMAT_A8B8G8R8_SINT_PACK32 = 56,
   VK_FORMAT_A8B8G8R8_SRGB_PACK32 = 57,
   VK_FORMAT_A2R10G10B10_UNORM_PACK32 = 58,
   VK_FORMAT_A2R10G10B10_SNORM_PACK32 = 59,
   VK_FORMAT_A2R10G10B10_USCALED_PACK32 = 60,
   VK_FORMAT_A2R10G10B10_SSCALED_PACK32 = 61,
   VK_FORMAT_A2R10G10B10_UINT_PACK32 = 62,
   VK_FORMAT_A2R10G10B10_SINT_PACK32 = 63,
   VK_FORMAT_A2B10G10R10_UNORM_PACK32 = 64,
   VK_FORMAT_A2B10G10R10_SNORM_PACK32 = 65,
   VK_FORMAT_A2B10G10R10_USCALED_PACK32 = 66,
   VK_FORMAT_A2B10G10R10_SSCALED_PACK32 = 67,
   VK_FORMAT_A2B10G10R10_UINT_PACK32 = 68,
   VK_FORMAT_A2B10G10R10_SINT_PACK32 = 69,
   VK_FORMAT_R16_UNORM = 70,
   VK_FORMAT_R16_SNORM = 71,
   VK_FORMAT_R16_USCALED = 72,
   VK_FORMAT_R16_SSCALED = 73,
   VK_FORMAT_R16_UINT = 74,
   VK_FORMAT_R16_SINT = 75,
   VK_FORMAT_R16_SFLOAT = 76,
   VK_FORMAT_R16G16_UNORM = 77,
   VK_FORMAT_R16G16_SNORM = 78,
   VK_FORMAT_R16G16_USCALED = 79,
   VK_FORMAT_R16G16_SSCALED = 80,
   VK_FORMAT_R16G16_UINT = 81,
   VK_FORMAT_R16G16_SINT = 82,
   VK_FORMAT_R16G16_SFLOAT = 83,
   VK_FORMAT_R16G16B16_UNORM = 84,
   VK_FORMAT_R16G16B16_SNORM = 85,
   VK_FORMAT_R16G16B16_USCALED = 86,
   VK_FORMAT_R16G16B16_SSCALED = 87,
   VK_FORMAT_R16G16B16_UINT = 88,
   VK_FORMAT_R16G16B16_SINT = 89,
   VK_FORMAT_R16G16B16_SFLOAT = 90,
   VK_FORMAT_R16G16B16A16_UNORM = 91,
   VK_FORMAT_R16G16B16A16_SNORM = 92,
   VK_FORMAT_R16G16B16A16_USCALED = 93,
   VK_FORMAT_R16G16B16A16_SSCALED = 94,
   VK_FORMAT_R16G16B16A16_UINT = 95,
   VK_FORMAT_R16G16B16A16_SINT = 96,
   VK_FORMAT_R16G16B16A16_SFLOAT = 97,
   VK_FORMAT_R32_UINT = 98,
   VK_FORMAT_R32_SINT = 99,
   VK_FORMAT_R32_SFLOAT = 100,
   VK_FORMAT_R32G32_UINT = 101,
   VK_FORMAT_R32G32_SINT = 102,
   VK_FORMAT_R32G32_SFLOAT = 103,
   VK_FORMAT_R32G32B32_UINT = 104,
   VK_FORMAT_R32G32B32_SINT = 105,
   VK_FORMAT_R32G32B32_SFLOAT = 106,
   VK_FORMAT_R32G32B32A32_UINT = 107,
   VK_FORMAT_R32G32B32A32_SINT = 108,
   VK_FORMAT_R32G32B32A32_SFLOAT = 109,
   VK_FORMAT_R64_UINT = 110,
   VK_FORMAT_R64_SINT = 111,
   VK_FORMAT_R64_SFLOAT = 112,
   VK_FORMAT_R64G64_UINT = 113,
   VK_FORMAT_R64G64_SINT = 114,
   VK_FORMAT_R64G64_SFLOAT = 115,
   VK_FORMAT_R64G64B64_UINT = 116,
   VK_FORMAT_R64G64B64_SINT = 117,
   VK_FORMAT_R64G64B64_SFLOAT = 118,
   VK_FORMAT_R64G64B64A64_UINT = 119,
   VK_FORMAT_R64G64B64A64_SINT = 120,
   VK_FORMAT_R64G64B64A64_SFLOAT = 121,
   VK_FORMAT_B10G11R11_UFLOAT_PACK32 = 122,
   VK_FORMAT_E5B9G9R9_UFLOAT_PACK32 = 123,
   VK_FORMAT_D16_UNORM = 124,
   VK_FORMAT_X8_D24_UNORM_PACK32 = 125,
   VK_FORMAT_D32_SFLOAT = 126,
   VK_FORMAT_S8_UINT = 127,
   VK_FORMAT_D16_UNORM_S8_UINT = 128,
   VK_FORMAT_D24_UNORM_S8_UINT = 129,
   VK_FORMAT_D32_SFLOAT_S8_UINT = 130,
   VK_FORMAT_BC1_RGB_UNORM_BLOCK = 131,
   VK_FORMAT_BC1_RGB_SRGB_BLOCK = 132,
   VK_FORMAT_BC1_RGBA_UNORM_BLOCK = 133,
   VK_FORMAT_BC1_RGBA_SRGB_BLOCK = 134,
   VK_FORMAT_BC2_UNORM_BLOCK = 135,
   VK_FORMAT_BC2_SRGB_BLOCK = 136,
   VK_FORMAT_BC3_UNORM_BLOCK = 137,
   VK_FORMAT_BC3_SRGB_BLOCK = 138,
   VK_FORMAT_BC4_UNORM_BLOCK = 139,
   VK_FORMAT_BC4_SNORM_BLOCK = 140,
   VK_FORMAT_BC5_UNORM_BLOCK = 141,
   VK_FORMAT_BC5_SNORM_BLOCK = 142,
   VK_FORMAT_BC6H_UFLOAT_BLOCK = 143,
   VK_FORMAT_BC6H_SFLOAT_BLOCK = 144,
   VK_FORMAT_BC7_UNORM_BLOCK = 145,
   VK_FORMAT_BC7_SRGB_BLOCK = 146,
   VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK = 147,
   VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK = 148,
   VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK = 149,
   VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK = 150,
   VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK = 151,
   VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK = 152,
   VK_FORMAT_EAC_R11_UNORM_BLOCK = 153,
   VK_FORMAT_EAC_R11_SNORM_BLOCK = 154,
   VK_FORMAT_EAC_R11G11_UNORM_BLOCK = 155,
   VK_FORMAT_EAC_R11G11_SNORM_BLOCK = 156,
   VK_FORMAT_ASTC_4x4_UNORM_BLOCK = 157,
   VK_FORMAT_ASTC_4x4_SRGB_BLOCK = 158,
   VK_FORMAT_ASTC_5x4_UNORM_BLOCK = 159,
   VK_FORMAT_ASTC_5x4_SRGB_BLOCK = 160,
   VK_FORMAT_ASTC_5x5_UNORM_BLOCK = 161,
   VK_FORMAT_ASTC_5x5_SRGB_BLOCK = 162,
   VK_FORMAT_ASTC_6x5_UNORM_BLOCK = 163,
   VK_FORMAT_ASTC_6x5_SRGB_BLOCK = 164,
   VK_FORMAT_ASTC_6x6_UNORM_BLOCK = 165,
   VK_FORMAT_ASTC_6x6_SRGB_BLOCK = 166,
   VK_FORMAT_ASTC_8x5_UNORM_BLOCK = 167,
   VK_FORMAT_ASTC_8x5_SRGB_BLOCK = 168,
   VK_FORMAT_ASTC_8x6_UNORM_BLOCK = 169,
   VK_FORMAT_ASTC_8x6_SRGB_BLOCK = 170,
   VK_FORMAT_ASTC_8x8_UNORM_BLOCK = 171,
   VK_FORMAT_ASTC_8x8_SRGB_BLOCK = 172,
   VK_FORMAT_ASTC_10x5_UNORM_BLOCK = 173,
   VK_FORMAT_ASTC_10x5_SRGB_BLOCK = 174,
   VK_FORMAT_ASTC_10x6_UNORM_BLOCK = 175,
   VK_FORMAT_ASTC_10x6_SRGB_BLOCK = 176,
   VK_FORMAT_ASTC_10x8_UNORM_BLOCK = 177,
   VK_FORMAT_ASTC_10x8_SRGB_BLOCK = 178,
   VK_FORMAT_ASTC_10x10_UNORM_BLOCK = 179,
   VK_FORMAT_ASTC_10x10_SRGB_BLOCK = 180,
   VK_FORMAT_ASTC_12x10_UNORM_BLOCK = 181,
   VK_FORMAT_ASTC_12x10_SRGB_BLOCK = 182,
   VK_FORMAT_ASTC_12x12_UNORM_BLOCK = 183,
   VK_FORMAT_ASTC_12x12_SRGB_BLOCK = 184,
   VK_FORMAT_G8B8G8R8_422_UNORM = 1000156000,
   VK_FORMAT_B8G8R8G8_422_UNORM = 1000156001,
   VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM = 1000156002,
   VK_FORMAT_G8_B8R8_2PLANE_420_UNORM = 1000156003,
   VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM = 1000156004,
   VK_FORMAT_G8_B8R8_2PLANE_422_UNORM = 1000156005,
   VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM = 1000156006,
   VK_FORMAT_R10X6_UNORM_PACK16 = 1000156007,
   VK_FORMAT_R10X6G10X6_UNORM_2PACK16 = 1000156008,
   VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16 = 1000156009,
   VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16 = 1000156010,
   VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16 = 1000156011,
   VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16 = 1000156012,
   VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16 = 1000156013,
   VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16 = 1000156014,
   VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16 = 1000156015,
   VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16 = 1000156016,
   VK_FORMAT_R12X4_UNORM_PACK16 = 1000156017,
   VK_FORMAT_R12X4G12X4_UNORM_2PACK16 = 1000156018,
   VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16 = 1000156019,
   VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16 = 1000156020,
   VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16 = 1000156021,
   VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16 = 1000156022,
   VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16 = 1000156023,
   VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16 = 1000156024,
   VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16 = 1000156025,
   VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16 = 1000156026,
   VK_FORMAT_G16B16G16R16_422_UNORM = 1000156027,
   VK_FORMAT_B16G16R16G16_422_UNORM = 1000156028,
   VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM = 1000156029,
   VK_FORMAT_G16_B16R16_2PLANE_420_UNORM = 1000156030,
   VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM = 1000156031,
   VK_FORMAT_G16_B16R16_2PLANE_422_UNORM = 1000156032,
   VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM = 1000156033,
   VK_FORMAT_PVRTC1_2BPP_UNORM_BLOCK_IMG = 1000054000,
   VK_FORMAT_PVRTC1_4BPP_UNORM_BLOCK_IMG = 1000054001,
   VK_FORMAT_PVRTC2_2BPP_UNORM_BLOCK_IMG = 1000054002,
   VK_FORMAT_PVRTC2_4BPP_UNORM_BLOCK_IMG = 1000054003,
   VK_FORMAT_PVRTC1_2BPP_SRGB_BLOCK_IMG = 1000054004,
   VK_FORMAT_PVRTC1_4BPP_SRGB_BLOCK_IMG = 1000054005,
   VK_FORMAT_PVRTC2_2BPP_SRGB_BLOCK_IMG = 1000054006,
   VK_FORMAT_PVRTC2_4BPP_SRGB_BLOCK_IMG = 1000054007,
   VK_FORMAT_G8B8G8R8_422_UNORM_KHR = VK_FORMAT_G8B8G8R8_422_UNORM,
   VK_FORMAT_B8G8R8G8_422_UNORM_KHR = VK_FORMAT_B8G8R8G8_422_UNORM,
   VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM_KHR = VK_FORMAT_G8_B8_R8_3PLANE_420_UNORM,
   VK_FORMAT_G8_B8R8_2PLANE_420_UNORM_KHR = VK_FORMAT_G8_B8R8_2PLANE_420_UNORM,
   VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM_KHR = VK_FORMAT_G8_B8_R8_3PLANE_422_UNORM,
   VK_FORMAT_G8_B8R8_2PLANE_422_UNORM_KHR = VK_FORMAT_G8_B8R8_2PLANE_422_UNORM,
   VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM_KHR = VK_FORMAT_G8_B8_R8_3PLANE_444_UNORM,
   VK_FORMAT_R10X6_UNORM_PACK16_KHR = VK_FORMAT_R10X6_UNORM_PACK16,
   VK_FORMAT_R10X6G10X6_UNORM_2PACK16_KHR = VK_FORMAT_R10X6G10X6_UNORM_2PACK16,
   VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16_KHR = VK_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16,
   VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16_KHR = VK_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16,
   VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16_KHR = VK_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16,
   VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16,
   VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16,
   VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16,
   VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16,
   VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16_KHR = VK_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16,
   VK_FORMAT_R12X4_UNORM_PACK16_KHR = VK_FORMAT_R12X4_UNORM_PACK16,
   VK_FORMAT_R12X4G12X4_UNORM_2PACK16_KHR = VK_FORMAT_R12X4G12X4_UNORM_2PACK16,
   VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16_KHR = VK_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16,
   VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16_KHR = VK_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16,
   VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16_KHR = VK_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16,
   VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16,
   VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16,
   VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16,
   VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16,
   VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16_KHR = VK_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16,
   VK_FORMAT_G16B16G16R16_422_UNORM_KHR = VK_FORMAT_G16B16G16R16_422_UNORM,
   VK_FORMAT_B16G16R16G16_422_UNORM_KHR = VK_FORMAT_B16G16R16G16_422_UNORM,
   VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM_KHR = VK_FORMAT_G16_B16_R16_3PLANE_420_UNORM,
   VK_FORMAT_G16_B16R16_2PLANE_420_UNORM_KHR = VK_FORMAT_G16_B16R16_2PLANE_420_UNORM,
   VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM_KHR = VK_FORMAT_G16_B16_R16_3PLANE_422_UNORM,
   VK_FORMAT_G16_B16R16_2PLANE_422_UNORM_KHR = VK_FORMAT_G16_B16R16_2PLANE_422_UNORM,
   VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM_KHR = VK_FORMAT_G16_B16_R16_3PLANE_444_UNORM,
} VkFormat;

typedef enum VkSystemAllocationScope {
   VK_SYSTEM_ALLOCATION_SCOPE_COMMAND = 0,
   VK_SYSTEM_ALLOCATION_SCOPE_OBJECT = 1,
   VK_SYSTEM_ALLOCATION_SCOPE_CACHE = 2,
   VK_SYSTEM_ALLOCATION_SCOPE_DEVICE = 3,
   VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE = 4,
   VK_SYSTEM_ALLOCATION_SCOPE_BEGIN_RANGE = VK_SYSTEM_ALLOCATION_SCOPE_COMMAND,
   VK_SYSTEM_ALLOCATION_SCOPE_END_RANGE = VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE,
   VK_SYSTEM_ALLOCATION_SCOPE_RANGE_SIZE = (VK_SYSTEM_ALLOCATION_SCOPE_INSTANCE - VK_SYSTEM_ALLOCATION_SCOPE_COMMAND + 1),
   VK_SYSTEM_ALLOCATION_SCOPE_MAX_ENUM = 0x7FFFFFFF
} VkSystemAllocationScope;

typedef enum VkInternalAllocationType {
   VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE = 0,
   VK_INTERNAL_ALLOCATION_TYPE_BEGIN_RANGE = VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE,
   VK_INTERNAL_ALLOCATION_TYPE_END_RANGE = VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE,
   VK_INTERNAL_ALLOCATION_TYPE_RANGE_SIZE = (VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE - VK_INTERNAL_ALLOCATION_TYPE_EXECUTABLE + 1),
   VK_INTERNAL_ALLOCATION_TYPE_MAX_ENUM = 0x7FFFFFFF
} VkInternalAllocationType;

typedef enum VkPhysicalDeviceType {
   VK_PHYSICAL_DEVICE_TYPE_OTHER = 0,
   VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU = 1,
   VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU = 2,
   VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU = 3,
   VK_PHYSICAL_DEVICE_TYPE_CPU = 4,
   VK_PHYSICAL_DEVICE_TYPE_BEGIN_RANGE = VK_PHYSICAL_DEVICE_TYPE_OTHER,
   VK_PHYSICAL_DEVICE_TYPE_END_RANGE = VK_PHYSICAL_DEVICE_TYPE_CPU,
   VK_PHYSICAL_DEVICE_TYPE_RANGE_SIZE = (VK_PHYSICAL_DEVICE_TYPE_CPU - VK_PHYSICAL_DEVICE_TYPE_OTHER + 1),
   VK_PHYSICAL_DEVICE_TYPE_MAX_ENUM = 0x7FFFFFFF
} VkPhysicalDeviceType;

typedef VkFlags VkInstanceCreateFlags;

typedef enum VkSampleCountFlagBits {
   VK_SAMPLE_COUNT_1_BIT = 0x00000001,
   VK_SAMPLE_COUNT_2_BIT = 0x00000002,
   VK_SAMPLE_COUNT_4_BIT = 0x00000004,
   VK_SAMPLE_COUNT_8_BIT = 0x00000008,
   VK_SAMPLE_COUNT_16_BIT = 0x00000010,
   VK_SAMPLE_COUNT_32_BIT = 0x00000020,
   VK_SAMPLE_COUNT_64_BIT = 0x00000040,
   VK_SAMPLE_COUNT_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} VkSampleCountFlagBits;
typedef VkFlags VkSampleCountFlags;

typedef enum VkQueueFlagBits {
   VK_QUEUE_GRAPHICS_BIT = 0x00000001,
   VK_QUEUE_COMPUTE_BIT = 0x00000002,
   VK_QUEUE_TRANSFER_BIT = 0x00000004,
   VK_QUEUE_SPARSE_BINDING_BIT = 0x00000008,
   VK_QUEUE_PROTECTED_BIT = 0x00000010,
   VK_QUEUE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} VkQueueFlagBits;
typedef VkFlags VkQueueFlags;

typedef enum VkMemoryHeapFlagBits {
   VK_MEMORY_HEAP_DEVICE_LOCAL_BIT = 0x00000001,
   VK_MEMORY_HEAP_MULTI_INSTANCE_BIT = 0x00000002,
   VK_MEMORY_HEAP_MULTI_INSTANCE_BIT_KHR = VK_MEMORY_HEAP_MULTI_INSTANCE_BIT,
   VK_MEMORY_HEAP_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} VkMemoryHeapFlagBits;
typedef VkFlags VkMemoryHeapFlags;
typedef VkFlags VkDeviceCreateFlags;

typedef enum VkDeviceQueueCreateFlagBits {
   VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT = 0x00000001,
   VK_DEVICE_QUEUE_CREATE_FLAG_BITS_MAX_ENUM = 0x7FFFFFFF
} VkDeviceQueueCreateFlagBits;
typedef VkFlags VkDeviceQueueCreateFlags;

typedef enum VkCommandPoolCreateFlagBits {
   VK_COMMAND_POOL_CREATE_TRANSIENT_BIT = 0x00000001,
   VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT = 0x00000002,
   VK_COMMAND_POOL_CREATE_PROTECTED_BIT = 0x00000004,
} VkCommandPoolCreateFlagBits;
typedef VkFlags VkCommandPoolCreateFlags;

typedef enum VkCommandPoolResetFlagBits {
   VK_COMMAND_POOL_RESET_RELEASE_RESOURCES_BIT = 0x00000001,
} VkCommandPoolResetFlagBits;
typedef VkFlags VkCommandPoolResetFlags;

typedef enum VkCommandBufferLevel {
   VK_COMMAND_BUFFER_LEVEL_PRIMARY = 0,
   VK_COMMAND_BUFFER_LEVEL_SECONDARY = 1,
} VkCommandBufferLevel;

typedef enum VkCommandBufferResetFlagBits {
   VK_COMMAND_BUFFER_RESET_RELEASE_RESOURCES_BIT = 0x00000001,
} VkCommandBufferResetFlagBits;
typedef VkFlags VkCommandBufferResetFlags;

typedef enum VkCommandBufferUsageFlagBits {
   VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT = 0x00000001,
   VK_COMMAND_BUFFER_USAGE_RENDER_PASS_CONTINUE_BIT = 0x00000002,
   VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT = 0x00000004,
} VkCommandBufferUsageFlagBits;
typedef VkFlags VkCommandBufferUsageFlags;

typedef enum VkFenceCreateFlagBits {
   VK_FENCE_CREATE_SIGNALED_BIT = 0x00000001,
} VkFenceCreateFlagBits;
typedef VkFlags VkFenceCreateFlags;

typedef VkFlags VkSemaphoreCreateFlags;

typedef enum VkQueryControlFlagBits {
   VK_QUERY_CONTROL_PRECISE_BIT = 0x00000001,
} VkQueryControlFlagBits;
typedef VkFlags VkQueryControlFlags;

typedef enum VkQueryPipelineStatisticFlagBits {
   VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_VERTICES_BIT = 0x00000001,
   VK_QUERY_PIPELINE_STATISTIC_INPUT_ASSEMBLY_PRIMITIVES_BIT = 0x00000002,
   VK_QUERY_PIPELINE_STATISTIC_VERTEX_SHADER_INVOCATIONS_BIT = 0x00000004,
   VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_INVOCATIONS_BIT = 0x00000008,
   VK_QUERY_PIPELINE_STATISTIC_GEOMETRY_SHADER_PRIMITIVES_BIT = 0x00000010,
   VK_QUERY_PIPELINE_STATISTIC_CLIPPING_INVOCATIONS_BIT = 0x00000020,
   VK_QUERY_PIPELINE_STATISTIC_CLIPPING_PRIMITIVES_BIT = 0x00000040,
   VK_QUERY_PIPELINE_STATISTIC_FRAGMENT_SHADER_INVOCATIONS_BIT = 0x00000080,
   VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_CONTROL_SHADER_PATCHES_BIT = 0x00000100,
   VK_QUERY_PIPELINE_STATISTIC_TESSELLATION_EVALUATION_SHADER_INVOCATIONS_BIT = 0x00000200,
   VK_QUERY_PIPELINE_STATISTIC_COMPUTE_SHADER_INVOCATIONS_BIT = 0x00000400,
} VkQueryPipelineStatisticFlagBits;
typedef VkFlags VkQueryPipelineStatisticFlags;

typedef enum VkPipelineStageFlagBits {
   VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT = 0x00000001,
   VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT = 0x00000002,
   VK_PIPELINE_STAGE_VERTEX_INPUT_BIT = 0x00000004,
   VK_PIPELINE_STAGE_VERTEX_SHADER_BIT = 0x00000008,
   VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT = 0x00000010,
   VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT = 0x00000020,
   VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT = 0x00000040,
   VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT = 0x00000080,
   VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT = 0x00000100,
   VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT = 0x00000200,
   VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT = 0x00000400,
   VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT = 0x00000800,
   VK_PIPELINE_STAGE_TRANSFER_BIT = 0x00001000,
   VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT = 0x00002000,
   VK_PIPELINE_STAGE_HOST_BIT = 0x00004000,
   VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT = 0x00008000,
   VK_PIPELINE_STAGE_ALL_COMMANDS_BIT = 0x00010000,
   VK_PIPELINE_STAGE_COMMAND_PROCESS_BIT_NVX = 0x00020000,
} VkPipelineStageFlagBits;
typedef VkFlags VkPipelineStageFlags;

typedef enum VkImageAspectFlagBits {
   VK_IMAGE_ASPECT_COLOR_BIT = 0x00000001,
   VK_IMAGE_ASPECT_DEPTH_BIT = 0x00000002,
   VK_IMAGE_ASPECT_STENCIL_BIT = 0x00000004,
   VK_IMAGE_ASPECT_METADATA_BIT = 0x00000008,
   VK_IMAGE_ASPECT_PLANE_0_BIT = 0x00000010,
   VK_IMAGE_ASPECT_PLANE_1_BIT = 0x00000020,
   VK_IMAGE_ASPECT_PLANE_2_BIT = 0x00000040,
   VK_IMAGE_ASPECT_PLANE_0_BIT_KHR = VK_IMAGE_ASPECT_PLANE_0_BIT,
   VK_IMAGE_ASPECT_PLANE_1_BIT_KHR = VK_IMAGE_ASPECT_PLANE_1_BIT,
   VK_IMAGE_ASPECT_PLANE_2_BIT_KHR = VK_IMAGE_ASPECT_PLANE_2_BIT,
} VkImageAspectFlagBits;
typedef VkFlags VkImageAspectFlags;

typedef VkFlags VkPipelineShaderStageCreateFlags;
typedef enum VkShaderStageFlagBits {
   VK_SHADER_STAGE_VERTEX_BIT = 0x00000001,
   VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT = 0x00000002,
   VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT = 0x00000004,
   VK_SHADER_STAGE_GEOMETRY_BIT = 0x00000008,
   VK_SHADER_STAGE_FRAGMENT_BIT = 0x00000010,
   VK_SHADER_STAGE_COMPUTE_BIT = 0x00000020,
   VK_SHADER_STAGE_ALL_GRAPHICS = 0x0000001F,
   VK_SHADER_STAGE_ALL = 0x7FFFFFFF,
} VkShaderStageFlagBits;
typedef VkFlags VkShaderStageFlags;

typedef VkFlags VkPipelineVertexInputStateCreateFlags;

typedef enum VkVertexInputRate {
   VK_VERTEX_INPUT_RATE_VERTEX = 0,
   VK_VERTEX_INPUT_RATE_INSTANCE = 1,
} VkVertexInputRate;

typedef enum VkImageLayout {
   VK_IMAGE_LAYOUT_UNDEFINED = 0,
   VK_IMAGE_LAYOUT_GENERAL = 1,
   VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL = 2,
   VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL = 3,
   VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL = 4,
   VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL = 5,
   VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL = 6,
   VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL = 7,
   VK_IMAGE_LAYOUT_PREINITIALIZED = 8,
   VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL = 1000117000,
   VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL = 1000117001,
   VK_IMAGE_LAYOUT_PRESENT_SRC_KHR = 1000001002,
   VK_IMAGE_LAYOUT_SHARED_PRESENT_KHR = 1000111000,
   VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL,
   VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL_KHR = VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL,
} VkImageLayout;

typedef VkFlags VkPipelineInputAssemblyStateCreateFlags;

typedef enum VkPrimitiveTopology {
   VK_PRIMITIVE_TOPOLOGY_POINT_LIST = 0,
   VK_PRIMITIVE_TOPOLOGY_LINE_LIST = 1,
   VK_PRIMITIVE_TOPOLOGY_LINE_STRIP = 2,
   VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3,
   VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 4,
   VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN = 5,
   VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY = 6,
   VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY = 7,
   VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY = 8,
   VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY = 9,
   VK_PRIMITIVE_TOPOLOGY_PATCH_LIST = 10,
} VkPrimitiveTopology;

typedef VkFlags VkPipelineTessellationStateCreateFlags;
typedef VkFlags VkPipelineViewportStateCreateFlags;
typedef VkFlags VkPipelineRasterizationStateCreateFlags;

typedef enum VkPolygonMode {
   VK_POLYGON_MODE_FILL = 0,
   VK_POLYGON_MODE_LINE = 1,
   VK_POLYGON_MODE_POINT = 2,
   VK_POLYGON_MODE_FILL_RECTANGLE_NV = 1000153000,
} VkPolygonMode;

typedef enum VkCullModeFlagBits {
   VK_CULL_MODE_NONE = 0,
   VK_CULL_MODE_FRONT_BIT = 0x00000001,
   VK_CULL_MODE_BACK_BIT = 0x00000002,
   VK_CULL_MODE_FRONT_AND_BACK = 0x00000003,
} VkCullModeFlagBits;
typedef VkFlags VkCullModeFlags;

typedef enum VkFrontFace {
   VK_FRONT_FACE_COUNTER_CLOCKWISE = 0,
   VK_FRONT_FACE_CLOCKWISE = 1,
} VkFrontFace;

typedef VkFlags VkPipelineMultisampleStateCreateFlags;
typedef VkFlags VkPipelineDepthStencilStateCreateFlags;

typedef enum VkCompareOp {
   VK_COMPARE_OP_NEVER = 0,
   VK_COMPARE_OP_LESS = 1,
   VK_COMPARE_OP_EQUAL = 2,
   VK_COMPARE_OP_LESS_OR_EQUAL = 3,
   VK_COMPARE_OP_GREATER = 4,
   VK_COMPARE_OP_NOT_EQUAL = 5,
   VK_COMPARE_OP_GREATER_OR_EQUAL = 6,
   VK_COMPARE_OP_ALWAYS = 7,
} VkCompareOp;

typedef enum VkStencilOp {
   VK_STENCIL_OP_KEEP = 0,
   VK_STENCIL_OP_ZERO = 1,
   VK_STENCIL_OP_REPLACE = 2,
   VK_STENCIL_OP_INCREMENT_AND_CLAMP = 3,
   VK_STENCIL_OP_DECREMENT_AND_CLAMP = 4,
   VK_STENCIL_OP_INVERT = 5,
   VK_STENCIL_OP_INCREMENT_AND_WRAP = 6,
   VK_STENCIL_OP_DECREMENT_AND_WRAP = 7,
} VkStencilOp;

typedef VkFlags VkPipelineColorBlendStateCreateFlags;
typedef enum VkLogicOp {
   VK_LOGIC_OP_CLEAR = 0,
   VK_LOGIC_OP_AND = 1,
   VK_LOGIC_OP_AND_REVERSE = 2,
   VK_LOGIC_OP_COPY = 3,
   VK_LOGIC_OP_AND_INVERTED = 4,
   VK_LOGIC_OP_NO_OP = 5,
   VK_LOGIC_OP_XOR = 6,
   VK_LOGIC_OP_OR = 7,
   VK_LOGIC_OP_NOR = 8,
   VK_LOGIC_OP_EQUIVALENT = 9,
   VK_LOGIC_OP_INVERT = 10,
   VK_LOGIC_OP_OR_REVERSE = 11,
   VK_LOGIC_OP_COPY_INVERTED = 12,
   VK_LOGIC_OP_OR_INVERTED = 13,
   VK_LOGIC_OP_NAND = 14,
   VK_LOGIC_OP_SET = 15,
} VkLogicOp;

typedef enum VkBlendFactor {
   VK_BLEND_FACTOR_ZERO = 0,
   VK_BLEND_FACTOR_ONE = 1,
   VK_BLEND_FACTOR_SRC_COLOR = 2,
   VK_BLEND_FACTOR_ONE_MINUS_SRC_COLOR = 3,
   VK_BLEND_FACTOR_DST_COLOR = 4,
   VK_BLEND_FACTOR_ONE_MINUS_DST_COLOR = 5,
   VK_BLEND_FACTOR_SRC_ALPHA = 6,
   VK_BLEND_FACTOR_ONE_MINUS_SRC_ALPHA = 7,
   VK_BLEND_FACTOR_DST_ALPHA = 8,
   VK_BLEND_FACTOR_ONE_MINUS_DST_ALPHA = 9,
   VK_BLEND_FACTOR_CONSTANT_COLOR = 10,
   VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_COLOR = 11,
   VK_BLEND_FACTOR_CONSTANT_ALPHA = 12,
   VK_BLEND_FACTOR_ONE_MINUS_CONSTANT_ALPHA = 13,
   VK_BLEND_FACTOR_SRC_ALPHA_SATURATE = 14,
   VK_BLEND_FACTOR_SRC1_COLOR = 15,
   VK_BLEND_FACTOR_ONE_MINUS_SRC1_COLOR = 16,
   VK_BLEND_FACTOR_SRC1_ALPHA = 17,
   VK_BLEND_FACTOR_ONE_MINUS_SRC1_ALPHA = 18,
} VkBlendFactor;

typedef enum VkBlendOp {
   VK_BLEND_OP_ADD = 0,
   VK_BLEND_OP_SUBTRACT = 1,
   VK_BLEND_OP_REVERSE_SUBTRACT = 2,
   VK_BLEND_OP_MIN = 3,
   VK_BLEND_OP_MAX = 4,
   VK_BLEND_OP_ZERO_EXT = 1000148000,
   VK_BLEND_OP_SRC_EXT = 1000148001,
   VK_BLEND_OP_DST_EXT = 1000148002,
   VK_BLEND_OP_SRC_OVER_EXT = 1000148003,
   VK_BLEND_OP_DST_OVER_EXT = 1000148004,
   VK_BLEND_OP_SRC_IN_EXT = 1000148005,
   VK_BLEND_OP_DST_IN_EXT = 1000148006,
   VK_BLEND_OP_SRC_OUT_EXT = 1000148007,
   VK_BLEND_OP_DST_OUT_EXT = 1000148008,
   VK_BLEND_OP_SRC_ATOP_EXT = 1000148009,
   VK_BLEND_OP_DST_ATOP_EXT = 1000148010,
   VK_BLEND_OP_XOR_EXT = 1000148011,
   VK_BLEND_OP_MULTIPLY_EXT = 1000148012,
   VK_BLEND_OP_SCREEN_EXT = 1000148013,
   VK_BLEND_OP_OVERLAY_EXT = 1000148014,
   VK_BLEND_OP_DARKEN_EXT = 1000148015,
   VK_BLEND_OP_LIGHTEN_EXT = 1000148016,
   VK_BLEND_OP_COLORDODGE_EXT = 1000148017,
   VK_BLEND_OP_COLORBURN_EXT = 1000148018,
   VK_BLEND_OP_HARDLIGHT_EXT = 1000148019,
   VK_BLEND_OP_SOFTLIGHT_EXT = 1000148020,
   VK_BLEND_OP_DIFFERENCE_EXT = 1000148021,
   VK_BLEND_OP_EXCLUSION_EXT = 1000148022,
   VK_BLEND_OP_INVERT_EXT = 1000148023,
   VK_BLEND_OP_INVERT_RGB_EXT = 1000148024,
   VK_BLEND_OP_LINEARDODGE_EXT = 1000148025,
   VK_BLEND_OP_LINEARBURN_EXT = 1000148026,
   VK_BLEND_OP_VIVIDLIGHT_EXT = 1000148027,
   VK_BLEND_OP_LINEARLIGHT_EXT = 1000148028,
   VK_BLEND_OP_PINLIGHT_EXT = 1000148029,
   VK_BLEND_OP_HARDMIX_EXT = 1000148030,
   VK_BLEND_OP_HSL_HUE_EXT = 1000148031,
   VK_BLEND_OP_HSL_SATURATION_EXT = 1000148032,
   VK_BLEND_OP_HSL_COLOR_EXT = 1000148033,
   VK_BLEND_OP_HSL_LUMINOSITY_EXT = 1000148034,
   VK_BLEND_OP_PLUS_EXT = 1000148035,
   VK_BLEND_OP_PLUS_CLAMPED_EXT = 1000148036,
   VK_BLEND_OP_PLUS_CLAMPED_ALPHA_EXT = 1000148037,
   VK_BLEND_OP_PLUS_DARKER_EXT = 1000148038,
   VK_BLEND_OP_MINUS_EXT = 1000148039,
   VK_BLEND_OP_MINUS_CLAMPED_EXT = 1000148040,
   VK_BLEND_OP_CONTRAST_EXT = 1000148041,
   VK_BLEND_OP_INVERT_OVG_EXT = 1000148042,
   VK_BLEND_OP_RED_EXT = 1000148043,
   VK_BLEND_OP_GREEN_EXT = 1000148044,
   VK_BLEND_OP_BLUE_EXT = 1000148045,
} VkBlendOp;

typedef enum VkColorComponentFlagBits {
   VK_COLOR_COMPONENT_R_BIT = 0x00000001,
   VK_COLOR_COMPONENT_G_BIT = 0x00000002,
   VK_COLOR_COMPONENT_B_BIT = 0x00000004,
   VK_COLOR_COMPONENT_A_BIT = 0x00000008,
} VkColorComponentFlagBits;
typedef VkFlags VkColorComponentFlags;

typedef VkFlags VkPipelineDynamicStateCreateFlags;
typedef enum VkDynamicState {
   VK_DYNAMIC_STATE_VIEWPORT = 0,
   VK_DYNAMIC_STATE_SCISSOR = 1,
   VK_DYNAMIC_STATE_LINE_WIDTH = 2,
   VK_DYNAMIC_STATE_DEPTH_BIAS = 3,
   VK_DYNAMIC_STATE_BLEND_CONSTANTS = 4,
   VK_DYNAMIC_STATE_DEPTH_BOUNDS = 5,
   VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK = 6,
   VK_DYNAMIC_STATE_STENCIL_WRITE_MASK = 7,
   VK_DYNAMIC_STATE_STENCIL_REFERENCE = 8,
   VK_DYNAMIC_STATE_VIEWPORT_W_SCALING_NV = 1000087000,
   VK_DYNAMIC_STATE_DISCARD_RECTANGLE_EXT = 1000099000,
   VK_DYNAMIC_STATE_SAMPLE_LOCATIONS_EXT = 1000143000,
} VkDynamicState;

typedef enum VkPipelineCreateFlagBits {
   VK_PIPELINE_CREATE_DISABLE_OPTIMIZATION_BIT = 0x00000001,
   VK_PIPELINE_CREATE_ALLOW_DERIVATIVES_BIT = 0x00000002,
   VK_PIPELINE_CREATE_DERIVATIVE_BIT = 0x00000004,
   VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT = 0x00000008,
   VK_PIPELINE_CREATE_DISPATCH_BASE = 0x00000010,
   VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT_KHR = VK_PIPELINE_CREATE_VIEW_INDEX_FROM_DEVICE_INDEX_BIT,
   VK_PIPELINE_CREATE_DISPATCH_BASE_KHR = VK_PIPELINE_CREATE_DISPATCH_BASE,
} VkPipelineCreateFlagBits;
typedef VkFlags VkPipelineCreateFlags;

typedef enum VkSharingMode {
   VK_SHARING_MODE_EXCLUSIVE = 0,
   VK_SHARING_MODE_CONCURRENT = 1,
} VkSharingMode;

typedef enum VkImageUsageFlagBits {
   VK_IMAGE_USAGE_TRANSFER_SRC_BIT = 0x00000001,
   VK_IMAGE_USAGE_TRANSFER_DST_BIT = 0x00000002,
   VK_IMAGE_USAGE_SAMPLED_BIT = 0x00000004,
   VK_IMAGE_USAGE_STORAGE_BIT = 0x00000008,
   VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT = 0x00000010,
   VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT = 0x00000020,
   VK_IMAGE_USAGE_TRANSIENT_ATTACHMENT_BIT = 0x00000040,
   VK_IMAGE_USAGE_INPUT_ATTACHMENT_BIT = 0x00000080,
} VkImageUsageFlagBits;
typedef VkFlags VkImageUsageFlags;

typedef enum VkImageType {
   VK_IMAGE_TYPE_1D = 0,
   VK_IMAGE_TYPE_2D = 1,
   VK_IMAGE_TYPE_3D = 2,
} VkImageType;

typedef VkFlags VkImageViewCreateFlags;

typedef enum VkImageViewType {
   VK_IMAGE_VIEW_TYPE_1D = 0,
   VK_IMAGE_VIEW_TYPE_2D = 1,
   VK_IMAGE_VIEW_TYPE_3D = 2,
   VK_IMAGE_VIEW_TYPE_CUBE = 3,
   VK_IMAGE_VIEW_TYPE_1D_ARRAY = 4,
   VK_IMAGE_VIEW_TYPE_2D_ARRAY = 5,
   VK_IMAGE_VIEW_TYPE_CUBE_ARRAY = 6,
} VkImageViewType;

typedef enum VkComponentSwizzle {
   VK_COMPONENT_SWIZZLE_IDENTITY = 0,
   VK_COMPONENT_SWIZZLE_ZERO = 1,
   VK_COMPONENT_SWIZZLE_ONE = 2,
   VK_COMPONENT_SWIZZLE_R = 3,
   VK_COMPONENT_SWIZZLE_G = 4,
   VK_COMPONENT_SWIZZLE_B = 5,
   VK_COMPONENT_SWIZZLE_A = 6,
} VkComponentSwizzle;

typedef VkFlags VkShaderModuleCreateFlags;
typedef VkFlags VkPipelineLayoutCreateFlags;

typedef enum VkPipelineBindPoint {
   VK_PIPELINE_BIND_POINT_GRAPHICS = 0,
   VK_PIPELINE_BIND_POINT_COMPUTE = 1,
} VkPipelineBindPoint;

typedef enum VkAccessFlagBits {
   VK_ACCESS_INDIRECT_COMMAND_READ_BIT = 0x00000001,
   VK_ACCESS_INDEX_READ_BIT = 0x00000002,
   VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT = 0x00000004,
   VK_ACCESS_UNIFORM_READ_BIT = 0x00000008,
   VK_ACCESS_INPUT_ATTACHMENT_READ_BIT = 0x00000010,
   VK_ACCESS_SHADER_READ_BIT = 0x00000020,
   VK_ACCESS_SHADER_WRITE_BIT = 0x00000040,
   VK_ACCESS_COLOR_ATTACHMENT_READ_BIT = 0x00000080,
   VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT = 0x00000100,
   VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT = 0x00000200,
   VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT = 0x00000400,
   VK_ACCESS_TRANSFER_READ_BIT = 0x00000800,
   VK_ACCESS_TRANSFER_WRITE_BIT = 0x00001000,
   VK_ACCESS_HOST_READ_BIT = 0x00002000,
   VK_ACCESS_HOST_WRITE_BIT = 0x00004000,
   VK_ACCESS_MEMORY_READ_BIT = 0x00008000,
   VK_ACCESS_MEMORY_WRITE_BIT = 0x00010000,
   VK_ACCESS_COMMAND_PROCESS_READ_BIT_NVX = 0x00020000,
   VK_ACCESS_COMMAND_PROCESS_WRITE_BIT_NVX = 0x00040000,
   VK_ACCESS_COLOR_ATTACHMENT_READ_NONCOHERENT_BIT_EXT = 0x00080000,
} VkAccessFlagBits;
typedef VkFlags VkAccessFlags;

typedef enum VkDependencyFlagBits {
   VK_DEPENDENCY_BY_REGION_BIT = 0x00000001,
   VK_DEPENDENCY_DEVICE_GROUP_BIT = 0x00000004,
   VK_DEPENDENCY_VIEW_LOCAL_BIT = 0x00000002,
   VK_DEPENDENCY_VIEW_LOCAL_BIT_KHR = VK_DEPENDENCY_VIEW_LOCAL_BIT,
   VK_DEPENDENCY_DEVICE_GROUP_BIT_KHR = VK_DEPENDENCY_DEVICE_GROUP_BIT,
} VkDependencyFlagBits;
typedef VkFlags VkDependencyFlags;

typedef enum VkAttachmentDescriptionFlagBits {
   VK_ATTACHMENT_DESCRIPTION_MAY_ALIAS_BIT = 0x00000001,
} VkAttachmentDescriptionFlagBits;
typedef VkFlags VkAttachmentDescriptionFlags;

typedef enum VkAttachmentLoadOp {
   VK_ATTACHMENT_LOAD_OP_LOAD = 0,
   VK_ATTACHMENT_LOAD_OP_CLEAR = 1,
   VK_ATTACHMENT_LOAD_OP_DONT_CARE = 2,
} VkAttachmentLoadOp;

typedef enum VkAttachmentStoreOp {
   VK_ATTACHMENT_STORE_OP_STORE = 0,
   VK_ATTACHMENT_STORE_OP_DONT_CARE = 1,
} VkAttachmentStoreOp;

typedef VkFlags VkRenderPassCreateFlags;

typedef enum VkSubpassDescriptionFlagBits {
   VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX = 0x00000001,
   VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX = 0x00000002,
} VkSubpassDescriptionFlagBits;
typedef VkFlags VkSubpassDescriptionFlags;

typedef enum VkSubpassContents {
   VK_SUBPASS_CONTENTS_INLINE = 0,
   VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS = 1,
} VkSubpassContents;

typedef VkFlags VkFramebufferCreateFlags;

typedef enum VkDeviceGroupPresentModeFlagBitsKHR {
   VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR = 0x00000001,
   VK_DEVICE_GROUP_PRESENT_MODE_REMOTE_BIT_KHR = 0x00000002,
   VK_DEVICE_GROUP_PRESENT_MODE_SUM_BIT_KHR = 0x00000004,
   VK_DEVICE_GROUP_PRESENT_MODE_LOCAL_MULTI_DEVICE_BIT_KHR = 0x00000008,
} VkDeviceGroupPresentModeFlagBitsKHR;
typedef VkFlags VkDeviceGroupPresentModeFlagsKHR;

typedef enum VkSwapchainCreateFlagBitsKHR {
   VK_SWAPCHAIN_CREATE_SPLIT_INSTANCE_BIND_REGIONS_BIT_KHR = 0x00000001,
   VK_SWAPCHAIN_CREATE_PROTECTED_BIT_KHR = 0x00000002,
} VkSwapchainCreateFlagBitsKHR;
typedef VkFlags VkSwapchainCreateFlagsKHR;

typedef enum VkColorSpaceKHR {
   VK_COLOR_SPACE_SRGB_NONLINEAR_KHR = 0,
   VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT = 1000104001,
   VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT = 1000104002,
   VK_COLOR_SPACE_DCI_P3_LINEAR_EXT = 1000104003,
   VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT = 1000104004,
   VK_COLOR_SPACE_BT709_LINEAR_EXT = 1000104005,
   VK_COLOR_SPACE_BT709_NONLINEAR_EXT = 1000104006,
   VK_COLOR_SPACE_BT2020_LINEAR_EXT = 1000104007,
   VK_COLOR_SPACE_HDR10_ST2084_EXT = 1000104008,
   VK_COLOR_SPACE_DOLBYVISION_EXT = 1000104009,
   VK_COLOR_SPACE_HDR10_HLG_EXT = 1000104010,
   VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT = 1000104011,
   VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT = 1000104012,
   VK_COLOR_SPACE_PASS_THROUGH_EXT = 1000104013,
   VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT = 1000104014,
} VkColorSpaceKHR;

typedef enum VkSurfaceTransformFlagBitsKHR {
   VK_SURFACE_TRANSFORM_IDENTITY_BIT_KHR = 0x00000001,
   VK_SURFACE_TRANSFORM_ROTATE_90_BIT_KHR = 0x00000002,
   VK_SURFACE_TRANSFORM_ROTATE_180_BIT_KHR = 0x00000004,
   VK_SURFACE_TRANSFORM_ROTATE_270_BIT_KHR = 0x00000008,
   VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_BIT_KHR = 0x00000010,
   VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_90_BIT_KHR = 0x00000020,
   VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_180_BIT_KHR = 0x00000040,
   VK_SURFACE_TRANSFORM_HORIZONTAL_MIRROR_ROTATE_270_BIT_KHR = 0x00000080,
   VK_SURFACE_TRANSFORM_INHERIT_BIT_KHR = 0x00000100,
} VkSurfaceTransformFlagBitsKHR;
typedef VkFlags VkSurfaceTransformFlagsKHR;

typedef enum VkCompositeAlphaFlagBitsKHR {
   VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR = 0x00000001,
   VK_COMPOSITE_ALPHA_PRE_MULTIPLIED_BIT_KHR = 0x00000002,
   VK_COMPOSITE_ALPHA_POST_MULTIPLIED_BIT_KHR = 0x00000004,
   VK_COMPOSITE_ALPHA_INHERIT_BIT_KHR = 0x00000008,
} VkCompositeAlphaFlagBitsKHR;
typedef VkFlags VkCompositeAlphaFlagsKHR;

typedef enum VkPresentModeKHR {
   VK_PRESENT_MODE_IMMEDIATE_KHR = 0,
   VK_PRESENT_MODE_MAILBOX_KHR = 1,
   VK_PRESENT_MODE_FIFO_KHR = 2,
   VK_PRESENT_MODE_FIFO_RELAXED_KHR = 3,
   VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR = 1000111000,
   VK_PRESENT_MODE_SHARED_CONTINUOUS_REFRESH_KHR = 1000111001,
} VkPresentModeKHR;

typedef struct VkOffset2D {
   int32_t    x;
   int32_t    y;
} VkOffset2D;

typedef struct VkOffset3D {
   int32_t    x;
   int32_t    y;
   int32_t    z;
} VkOffset3D;

typedef struct VkExtent2D {
   uint32_t    width;
   uint32_t    height;
} VkExtent2D;

typedef struct VkExtent3D {
   uint32_t    width;
   uint32_t    height;
   uint32_t    depth;
} VkExtent3D;

typedef struct VkRect2D {
   VkOffset2D    offset;
   VkExtent2D    extent;
} VkRect2D;

typedef struct VkApplicationInfo {
   VkStructureType    sType;
   const void*        pNext;
   const char*        pApplicationName;
   uint32_t           applicationVersion;
   const char*        pEngineName;
   uint32_t           engineVersion;
   uint32_t           apiVersion;
} VkApplicationInfo;

typedef struct VkInstanceCreateInfo {
   VkStructureType             sType;
   const void*                 pNext;
   VkInstanceCreateFlags       flags;
   const VkApplicationInfo*    pApplicationInfo;
   uint32_t                    enabledLayerCount;
   const char* const*          ppEnabledLayerNames;
   uint32_t                    enabledExtensionCount;
   const char* const*          ppEnabledExtensionNames;
} VkInstanceCreateInfo;

typedef void* (VKAPI_PTR *PFN_vkAllocationFunction)(
   void*                                       pUserData,
   size_t                                      size,
   size_t                                      alignment,
   VkSystemAllocationScope                     allocationScope);

typedef void* (VKAPI_PTR *PFN_vkReallocationFunction)(
   void*                                       pUserData,
   void*                                       pOriginal,
   size_t                                      size,
   size_t                                      alignment,
   VkSystemAllocationScope                     allocationScope);

typedef void (VKAPI_PTR *PFN_vkFreeFunction)(
   void*                                       pUserData,
   void*                                       pMemory);

typedef void (VKAPI_PTR *PFN_vkInternalAllocationNotification)(
   void*                                       pUserData,
   size_t                                      size,
   VkInternalAllocationType                    allocationType,
   VkSystemAllocationScope                     allocationScope);

typedef void (VKAPI_PTR *PFN_vkInternalFreeNotification)(
   void*                                       pUserData,
   size_t                                      size,
   VkInternalAllocationType                    allocationType,
   VkSystemAllocationScope                     allocationScope);

typedef struct VkAllocationCallbacks {
   void*                                   pUserData;
   PFN_vkAllocationFunction                pfnAllocation;
   PFN_vkReallocationFunction              pfnReallocation;
   PFN_vkFreeFunction                      pfnFree;
   PFN_vkInternalAllocationNotification    pfnInternalAllocation;
   PFN_vkInternalFreeNotification          pfnInternalFree;
} VkAllocationCallbacks;

typedef struct VkPhysicalDeviceLimits {
   uint32_t              maxImageDimension1D;
   uint32_t              maxImageDimension2D;
   uint32_t              maxImageDimension3D;
   uint32_t              maxImageDimensionCube;
   uint32_t              maxImageArrayLayers;
   uint32_t              maxTexelBufferElements;
   uint32_t              maxUniformBufferRange;
   uint32_t              maxStorageBufferRange;
   uint32_t              maxPushConstantsSize;
   uint32_t              maxMemoryAllocationCount;
   uint32_t              maxSamplerAllocationCount;
   VkDeviceSize          bufferImageGranularity;
   VkDeviceSize          sparseAddressSpaceSize;
   uint32_t              maxBoundDescriptorSets;
   uint32_t              maxPerStageDescriptorSamplers;
   uint32_t              maxPerStageDescriptorUniformBuffers;
   uint32_t              maxPerStageDescriptorStorageBuffers;
   uint32_t              maxPerStageDescriptorSampledImages;
   uint32_t              maxPerStageDescriptorStorageImages;
   uint32_t              maxPerStageDescriptorInputAttachments;
   uint32_t              maxPerStageResources;
   uint32_t              maxDescriptorSetSamplers;
   uint32_t              maxDescriptorSetUniformBuffers;
   uint32_t              maxDescriptorSetUniformBuffersDynamic;
   uint32_t              maxDescriptorSetStorageBuffers;
   uint32_t              maxDescriptorSetStorageBuffersDynamic;
   uint32_t              maxDescriptorSetSampledImages;
   uint32_t              maxDescriptorSetStorageImages;
   uint32_t              maxDescriptorSetInputAttachments;
   uint32_t              maxVertexInputAttributes;
   uint32_t              maxVertexInputBindings;
   uint32_t              maxVertexInputAttributeOffset;
   uint32_t              maxVertexInputBindingStride;
   uint32_t              maxVertexOutputComponents;
   uint32_t              maxTessellationGenerationLevel;
   uint32_t              maxTessellationPatchSize;
   uint32_t              maxTessellationControlPerVertexInputComponents;
   uint32_t              maxTessellationControlPerVertexOutputComponents;
   uint32_t              maxTessellationControlPerPatchOutputComponents;
   uint32_t              maxTessellationControlTotalOutputComponents;
   uint32_t              maxTessellationEvaluationInputComponents;
   uint32_t              maxTessellationEvaluationOutputComponents;
   uint32_t              maxGeometryShaderInvocations;
   uint32_t              maxGeometryInputComponents;
   uint32_t              maxGeometryOutputComponents;
   uint32_t              maxGeometryOutputVertices;
   uint32_t              maxGeometryTotalOutputComponents;
   uint32_t              maxFragmentInputComponents;
   uint32_t              maxFragmentOutputAttachments;
   uint32_t              maxFragmentDualSrcAttachments;
   uint32_t              maxFragmentCombinedOutputResources;
   uint32_t              maxComputeSharedMemorySize;
   uint32_t              maxComputeWorkGroupCount[3];
   uint32_t              maxComputeWorkGroupInvocations;
   uint32_t              maxComputeWorkGroupSize[3];
   uint32_t              subPixelPrecisionBits;
   uint32_t              subTexelPrecisionBits;
   uint32_t              mipmapPrecisionBits;
   uint32_t              maxDrawIndexedIndexValue;
   uint32_t              maxDrawIndirectCount;
   float                 maxSamplerLodBias;
   float                 maxSamplerAnisotropy;
   uint32_t              maxViewports;
   uint32_t              maxViewportDimensions[2];
   float                 viewportBoundsRange[2];
   uint32_t              viewportSubPixelBits;
   size_t                minMemoryMapAlignment;
   VkDeviceSize          minTexelBufferOffsetAlignment;
   VkDeviceSize          minUniformBufferOffsetAlignment;
   VkDeviceSize          minStorageBufferOffsetAlignment;
   int32_t               minTexelOffset;
   uint32_t              maxTexelOffset;
   int32_t               minTexelGatherOffset;
   uint32_t              maxTexelGatherOffset;
   float                 minInterpolationOffset;
   float                 maxInterpolationOffset;
   uint32_t              subPixelInterpolationOffsetBits;
   uint32_t              maxFramebufferWidth;
   uint32_t              maxFramebufferHeight;
   uint32_t              maxFramebufferLayers;
   VkSampleCountFlags    framebufferColorSampleCounts;
   VkSampleCountFlags    framebufferDepthSampleCounts;
   VkSampleCountFlags    framebufferStencilSampleCounts;
   VkSampleCountFlags    framebufferNoAttachmentsSampleCounts;
   uint32_t              maxColorAttachments;
   VkSampleCountFlags    sampledImageColorSampleCounts;
   VkSampleCountFlags    sampledImageIntegerSampleCounts;
   VkSampleCountFlags    sampledImageDepthSampleCounts;
   VkSampleCountFlags    sampledImageStencilSampleCounts;
   VkSampleCountFlags    storageImageSampleCounts;
   uint32_t              maxSampleMaskWords;
   VkBool32              timestampComputeAndGraphics;
   float                 timestampPeriod;
   uint32_t              maxClipDistances;
   uint32_t              maxCullDistances;
   uint32_t              maxCombinedClipAndCullDistances;
   uint32_t              discreteQueuePriorities;
   float                 pointSizeRange[2];
   float                 lineWidthRange[2];
   float                 pointSizeGranularity;
   float                 lineWidthGranularity;
   VkBool32              strictLines;
   VkBool32              standardSampleLocations;
   VkDeviceSize          optimalBufferCopyOffsetAlignment;
   VkDeviceSize          optimalBufferCopyRowPitchAlignment;
   VkDeviceSize          nonCoherentAtomSize;
} VkPhysicalDeviceLimits;

typedef struct VkPhysicalDeviceSparseProperties {
   VkBool32    residencyStandard2DBlockShape;
   VkBool32    residencyStandard2DMultisampleBlockShape;
   VkBool32    residencyStandard3DBlockShape;
   VkBool32    residencyAlignedMipSize;
   VkBool32    residencyNonResidentStrict;
} VkPhysicalDeviceSparseProperties;

typedef struct VkPhysicalDeviceProperties {
   uint32_t                            apiVersion;
   uint32_t                            driverVersion;
   uint32_t                            vendorID;
   uint32_t                            deviceID;
   VkPhysicalDeviceType                deviceType;
   char                                deviceName[VK_MAX_PHYSICAL_DEVICE_NAME_SIZE];
   uint8_t                             pipelineCacheUUID[VK_UUID_SIZE];
   VkPhysicalDeviceLimits              limits;
   VkPhysicalDeviceSparseProperties    sparseProperties;
} VkPhysicalDeviceProperties;

typedef struct VkPhysicalDeviceFeatures {
   VkBool32    robustBufferAccess;
   VkBool32    fullDrawIndexUint32;
   VkBool32    imageCubeArray;
   VkBool32    independentBlend;
   VkBool32    geometryShader;
   VkBool32    tessellationShader;
   VkBool32    sampleRateShading;
   VkBool32    dualSrcBlend;
   VkBool32    logicOp;
   VkBool32    multiDrawIndirect;
   VkBool32    drawIndirectFirstInstance;
   VkBool32    depthClamp;
   VkBool32    depthBiasClamp;
   VkBool32    fillModeNonSolid;
   VkBool32    depthBounds;
   VkBool32    wideLines;
   VkBool32    largePoints;
   VkBool32    alphaToOne;
   VkBool32    multiViewport;
   VkBool32    samplerAnisotropy;
   VkBool32    textureCompressionETC2;
   VkBool32    textureCompressionASTC_LDR;
   VkBool32    textureCompressionBC;
   VkBool32    occlusionQueryPrecise;
   VkBool32    pipelineStatisticsQuery;
   VkBool32    vertexPipelineStoresAndAtomics;
   VkBool32    fragmentStoresAndAtomics;
   VkBool32    shaderTessellationAndGeometryPointSize;
   VkBool32    shaderImageGatherExtended;
   VkBool32    shaderStorageImageExtendedFormats;
   VkBool32    shaderStorageImageMultisample;
   VkBool32    shaderStorageImageReadWithoutFormat;
   VkBool32    shaderStorageImageWriteWithoutFormat;
   VkBool32    shaderUniformBufferArrayDynamicIndexing;
   VkBool32    shaderSampledImageArrayDynamicIndexing;
   VkBool32    shaderStorageBufferArrayDynamicIndexing;
   VkBool32    shaderStorageImageArrayDynamicIndexing;
   VkBool32    shaderClipDistance;
   VkBool32    shaderCullDistance;
   VkBool32    shaderFloat64;
   VkBool32    shaderInt64;
   VkBool32    shaderInt16;
   VkBool32    shaderResourceResidency;
   VkBool32    shaderResourceMinLod;
   VkBool32    sparseBinding;
   VkBool32    sparseResidencyBuffer;
   VkBool32    sparseResidencyImage2D;
   VkBool32    sparseResidencyImage3D;
   VkBool32    sparseResidency2Samples;
   VkBool32    sparseResidency4Samples;
   VkBool32    sparseResidency8Samples;
   VkBool32    sparseResidency16Samples;
   VkBool32    sparseResidencyAliased;
   VkBool32    variableMultisampleRate;
   VkBool32    inheritedQueries;
} VkPhysicalDeviceFeatures;

typedef struct VkQueueFamilyProperties {
   VkQueueFlags    queueFlags;
   uint32_t        queueCount;
   uint32_t        timestampValidBits;
   VkExtent3D      minImageTransferGranularity;
} VkQueueFamilyProperties;

typedef struct VkDeviceQueueCreateInfo {
   VkStructureType             sType;
   const void*                 pNext;
   VkDeviceQueueCreateFlags    flags;
   uint32_t                    queueFamilyIndex;
   uint32_t                    queueCount;
   const float*                pQueuePriorities;
} VkDeviceQueueCreateInfo;

typedef struct VkDeviceCreateInfo {
   VkStructureType                    sType;
   const void*                        pNext;
   VkDeviceCreateFlags                flags;
   uint32_t                           queueCreateInfoCount;
   const VkDeviceQueueCreateInfo*     pQueueCreateInfos;
   uint32_t                           enabledLayerCount;
   const char* const*                 ppEnabledLayerNames;
   uint32_t                           enabledExtensionCount;
   const char* const*                 ppEnabledExtensionNames;
   const VkPhysicalDeviceFeatures*    pEnabledFeatures;
} VkDeviceCreateInfo;

typedef struct VkCommandPoolCreateInfo {
   VkStructureType             sType;
   const void*                 pNext;
   VkCommandPoolCreateFlags    flags;
   uint32_t                    queueFamilyIndex;
} VkCommandPoolCreateInfo;

typedef struct VkCommandBufferAllocateInfo {
   VkStructureType         sType;
   const void*             pNext;
   VkCommandPool           commandPool;
   VkCommandBufferLevel    level;
   uint32_t                commandBufferCount;
} VkCommandBufferAllocateInfo;

typedef struct VkCommandBufferInheritanceInfo {
   VkStructureType                  sType;
   const void*                      pNext;
   VkRenderPass                     renderPass;
   uint32_t                         subpass;
   VkFramebuffer                    framebuffer;
   VkBool32                         occlusionQueryEnable;
   VkQueryControlFlags              queryFlags;
   VkQueryPipelineStatisticFlags    pipelineStatistics;
} VkCommandBufferInheritanceInfo;

typedef struct VkCommandBufferBeginInfo {
   VkStructureType                          sType;
   const void*                              pNext;
   VkCommandBufferUsageFlags                flags;
   const VkCommandBufferInheritanceInfo*    pInheritanceInfo;
} VkCommandBufferBeginInfo;

typedef struct VkFenceCreateInfo {
   VkStructureType       sType;
   const void*           pNext;
   VkFenceCreateFlags    flags;
} VkFenceCreateInfo;

typedef struct VkSemaphoreCreateInfo {
   VkStructureType           sType;
   const void*               pNext;
   VkSemaphoreCreateFlags    flags;
} VkSemaphoreCreateInfo;

typedef struct VkSubmitInfo {
   VkStructureType                sType;
   const void*                    pNext;
   uint32_t                       waitSemaphoreCount;
   const VkSemaphore*             pWaitSemaphores;
   const VkPipelineStageFlags*    pWaitDstStageMask;
   uint32_t                       commandBufferCount;
   const VkCommandBuffer*         pCommandBuffers;
   uint32_t                       signalSemaphoreCount;
   const VkSemaphore*             pSignalSemaphores;
} VkSubmitInfo;

typedef struct VkSpecializationMapEntry {
   uint32_t    constantID;
   uint32_t    offset;
   size_t      size;
} VkSpecializationMapEntry;

typedef struct VkSpecializationInfo {
   uint32_t                           mapEntryCount;
   const VkSpecializationMapEntry*    pMapEntries;
   size_t                             dataSize;
   const void*                        pData;
} VkSpecializationInfo;

typedef struct VkPipelineShaderStageCreateInfo {
   VkStructureType                     sType;
   const void*                         pNext;
   VkPipelineShaderStageCreateFlags    flags;
   VkShaderStageFlagBits               stage;
   VkShaderModule                      module;
   const char*                         pName;
   const VkSpecializationInfo*         pSpecializationInfo;
} VkPipelineShaderStageCreateInfo;

typedef struct VkVertexInputBindingDescription {
   uint32_t             binding;
   uint32_t             stride;
   VkVertexInputRate    inputRate;
} VkVertexInputBindingDescription;

typedef struct VkVertexInputAttributeDescription {
   uint32_t    location;
   uint32_t    binding;
   VkFormat    format;
   uint32_t    offset;
} VkVertexInputAttributeDescription;

typedef struct VkPipelineVertexInputStateCreateInfo {
   VkStructureType                             sType;
   const void*                                 pNext;
   VkPipelineVertexInputStateCreateFlags       flags;
   uint32_t                                    vertexBindingDescriptionCount;
   const VkVertexInputBindingDescription*      pVertexBindingDescriptions;
   uint32_t                                    vertexAttributeDescriptionCount;
   const VkVertexInputAttributeDescription*    pVertexAttributeDescriptions;
} VkPipelineVertexInputStateCreateInfo;

typedef struct VkPipelineInputAssemblyStateCreateInfo {
   VkStructureType                            sType;
   const void*                                pNext;
   VkPipelineInputAssemblyStateCreateFlags    flags;
   VkPrimitiveTopology                        topology;
   VkBool32                                   primitiveRestartEnable;
} VkPipelineInputAssemblyStateCreateInfo;

typedef struct VkPipelineTessellationStateCreateInfo {
   VkStructureType                           sType;
   const void*                               pNext;
   VkPipelineTessellationStateCreateFlags    flags;
   uint32_t                                  patchControlPoints;
} VkPipelineTessellationStateCreateInfo;

typedef struct VkViewport {
   float    x;
   float    y;
   float    width;
   float    height;
   float    minDepth;
   float    maxDepth;
} VkViewport;

typedef struct VkPipelineViewportStateCreateInfo {
   VkStructureType                       sType;
   const void*                           pNext;
   VkPipelineViewportStateCreateFlags    flags;
   uint32_t                              viewportCount;
   const VkViewport*                     pViewports;
   uint32_t                              scissorCount;
   const VkRect2D*                       pScissors;
} VkPipelineViewportStateCreateInfo;

typedef struct VkPipelineRasterizationStateCreateInfo {
   VkStructureType                            sType;
   const void*                                pNext;
   VkPipelineRasterizationStateCreateFlags    flags;
   VkBool32                                   depthClampEnable;
   VkBool32                                   rasterizerDiscardEnable;
   VkPolygonMode                              polygonMode;
   VkCullModeFlags                            cullMode;
   VkFrontFace                                frontFace;
   VkBool32                                   depthBiasEnable;
   float                                      depthBiasConstantFactor;
   float                                      depthBiasClamp;
   float                                      depthBiasSlopeFactor;
   float                                      lineWidth;
} VkPipelineRasterizationStateCreateInfo;

typedef struct VkPipelineMultisampleStateCreateInfo {
   VkStructureType                          sType;
   const void*                              pNext;
   VkPipelineMultisampleStateCreateFlags    flags;
   VkSampleCountFlagBits                    rasterizationSamples;
   VkBool32                                 sampleShadingEnable;
   float                                    minSampleShading;
   const VkSampleMask*                      pSampleMask;
   VkBool32                                 alphaToCoverageEnable;
   VkBool32                                 alphaToOneEnable;
} VkPipelineMultisampleStateCreateInfo;

typedef struct VkStencilOpState {
   VkStencilOp    failOp;
   VkStencilOp    passOp;
   VkStencilOp    depthFailOp;
   VkCompareOp    compareOp;
   uint32_t       compareMask;
   uint32_t       writeMask;
   uint32_t       reference;
} VkStencilOpState;

typedef struct VkPipelineDepthStencilStateCreateInfo {
   VkStructureType                           sType;
   const void*                               pNext;
   VkPipelineDepthStencilStateCreateFlags    flags;
   VkBool32                                  depthTestEnable;
   VkBool32                                  depthWriteEnable;
   VkCompareOp                               depthCompareOp;
   VkBool32                                  depthBoundsTestEnable;
   VkBool32                                  stencilTestEnable;
   VkStencilOpState                          front;
   VkStencilOpState                          back;
   float                                     minDepthBounds;
   float                                     maxDepthBounds;
} VkPipelineDepthStencilStateCreateInfo;

typedef struct VkPipelineColorBlendAttachmentState {
   VkBool32                 blendEnable;
   VkBlendFactor            srcColorBlendFactor;
   VkBlendFactor            dstColorBlendFactor;
   VkBlendOp                colorBlendOp;
   VkBlendFactor            srcAlphaBlendFactor;
   VkBlendFactor            dstAlphaBlendFactor;
   VkBlendOp                alphaBlendOp;
   VkColorComponentFlags    colorWriteMask;
} VkPipelineColorBlendAttachmentState;

typedef struct VkPipelineColorBlendStateCreateInfo {
   VkStructureType                               sType;
   const void*                                   pNext;
   VkPipelineColorBlendStateCreateFlags          flags;
   VkBool32                                      logicOpEnable;
   VkLogicOp                                     logicOp;
   uint32_t                                      attachmentCount;
   const VkPipelineColorBlendAttachmentState*    pAttachments;
   float                                         blendConstants[4];
} VkPipelineColorBlendStateCreateInfo;

typedef struct VkPipelineDynamicStateCreateInfo {
   VkStructureType                      sType;
   const void*                          pNext;
   VkPipelineDynamicStateCreateFlags    flags;
   uint32_t                             dynamicStateCount;
   const VkDynamicState*                pDynamicStates;
} VkPipelineDynamicStateCreateInfo;

typedef struct VkGraphicsPipelineCreateInfo {
   VkStructureType                                  sType;
   const void*                                      pNext;
   VkPipelineCreateFlags                            flags;
   uint32_t                                         stageCount;
   const VkPipelineShaderStageCreateInfo*           pStages;
   const VkPipelineVertexInputStateCreateInfo*      pVertexInputState;
   const VkPipelineInputAssemblyStateCreateInfo*    pInputAssemblyState;
   const VkPipelineTessellationStateCreateInfo*     pTessellationState;
   const VkPipelineViewportStateCreateInfo*         pViewportState;
   const VkPipelineRasterizationStateCreateInfo*    pRasterizationState;
   const VkPipelineMultisampleStateCreateInfo*      pMultisampleState;
   const VkPipelineDepthStencilStateCreateInfo*     pDepthStencilState;
   const VkPipelineColorBlendStateCreateInfo*       pColorBlendState;
   const VkPipelineDynamicStateCreateInfo*          pDynamicState;
   VkPipelineLayout                                 layout;
   VkRenderPass                                     renderPass;
   uint32_t                                         subpass;
   VkPipeline                                       basePipelineHandle;
   int32_t                                          basePipelineIndex;
} VkGraphicsPipelineCreateInfo;

typedef struct VkImageSubresourceRange {
   VkImageAspectFlags    aspectMask;
   uint32_t              baseMipLevel;
   uint32_t              levelCount;
   uint32_t              baseArrayLayer;
   uint32_t              layerCount;
} VkImageSubresourceRange;

typedef struct VkComponentMapping {
   VkComponentSwizzle    r;
   VkComponentSwizzle    g;
   VkComponentSwizzle    b;
   VkComponentSwizzle    a;
} VkComponentMapping;

typedef struct VkImageViewCreateInfo {
   VkStructureType            sType;
   const void*                pNext;
   VkImageViewCreateFlags     flags;
   VkImage                    image;
   VkImageViewType            viewType;
   VkFormat                   format;
   VkComponentMapping         components;
   VkImageSubresourceRange    subresourceRange;
} VkImageViewCreateInfo;

typedef struct VkShaderModuleCreateInfo {
   VkStructureType              sType;
   const void*                  pNext;
   VkShaderModuleCreateFlags    flags;
   size_t                       codeSize;
   const uint32_t*              pCode;
} VkShaderModuleCreateInfo;

typedef struct VkPushConstantRange {
   VkShaderStageFlags    stageFlags;
   uint32_t              offset;
   uint32_t              size;
} VkPushConstantRange;

typedef struct VkPipelineLayoutCreateInfo {
   VkStructureType                 sType;
   const void*                     pNext;
   VkPipelineLayoutCreateFlags     flags;
   uint32_t                        setLayoutCount;
   const VkDescriptorSetLayout*    pSetLayouts;
   uint32_t                        pushConstantRangeCount;
   const VkPushConstantRange*      pPushConstantRanges;
} VkPipelineLayoutCreateInfo;

typedef struct VkAttachmentReference {
   uint32_t         attachment;
   VkImageLayout    layout;
} VkAttachmentReference;

typedef union VkClearColorValue {
   float       float32[4];
   int32_t     int32[4];
   uint32_t    uint32[4];
} VkClearColorValue;

typedef struct VkClearDepthStencilValue {
   float       depth;
   uint32_t    stencil;
} VkClearDepthStencilValue;

typedef union VkClearValue {
   VkClearColorValue           color;
   VkClearDepthStencilValue    depthStencil;
} VkClearValue;

typedef struct VkSubpassDescription {
   VkSubpassDescriptionFlags       flags;
   VkPipelineBindPoint             pipelineBindPoint;
   uint32_t                        inputAttachmentCount;
   const VkAttachmentReference*    pInputAttachments;
   uint32_t                        colorAttachmentCount;
   const VkAttachmentReference*    pColorAttachments;
   const VkAttachmentReference*    pResolveAttachments;
   const VkAttachmentReference*    pDepthStencilAttachment;
   uint32_t                        preserveAttachmentCount;
   const uint32_t*                 pPreserveAttachments;
} VkSubpassDescription;

typedef struct VkAttachmentDescription {
   VkAttachmentDescriptionFlags    flags;
   VkFormat                        format;
   VkSampleCountFlagBits           samples;
   VkAttachmentLoadOp              loadOp;
   VkAttachmentStoreOp             storeOp;
   VkAttachmentLoadOp              stencilLoadOp;
   VkAttachmentStoreOp             stencilStoreOp;
   VkImageLayout                   initialLayout;
   VkImageLayout                   finalLayout;
} VkAttachmentDescription;

typedef struct VkSubpassDependency {
   uint32_t                srcSubpass;
   uint32_t                dstSubpass;
   VkPipelineStageFlags    srcStageMask;
   VkPipelineStageFlags    dstStageMask;
   VkAccessFlags           srcAccessMask;
   VkAccessFlags           dstAccessMask;
   VkDependencyFlags       dependencyFlags;
} VkSubpassDependency;

typedef struct VkRenderPassCreateInfo {
   VkStructureType                   sType;
   const void*                       pNext;
   VkRenderPassCreateFlags           flags;
   uint32_t                          attachmentCount;
   const VkAttachmentDescription*    pAttachments;
   uint32_t                          subpassCount;
   const VkSubpassDescription*       pSubpasses;
   uint32_t                          dependencyCount;
   const VkSubpassDependency*        pDependencies;
} VkRenderPassCreateInfo;

typedef struct VkRenderPassBeginInfo {
   VkStructureType        sType;
   const void*            pNext;
   VkRenderPass           renderPass;
   VkFramebuffer          framebuffer;
   VkRect2D               renderArea;
   uint32_t               clearValueCount;
   const VkClearValue*    pClearValues;
} VkRenderPassBeginInfo;

typedef struct VkFramebufferCreateInfo {
   VkStructureType             sType;
   const void*                 pNext;
   VkFramebufferCreateFlags    flags;
   VkRenderPass                renderPass;
   uint32_t                    attachmentCount;
   const VkImageView*          pAttachments;
   uint32_t                    width;
   uint32_t                    height;
   uint32_t                    layers;
} VkFramebufferCreateInfo;

typedef struct VkClearRect {
   VkRect2D    rect;
   uint32_t    baseArrayLayer;
   uint32_t    layerCount;
} VkClearRect;

typedef struct VkClearAttachment {
   VkImageAspectFlags    aspectMask;
   uint32_t              colorAttachment;
   VkClearValue          clearValue;
} VkClearAttachment;

typedef struct VkDrawIndirectCommand {
   uint32_t    vertexCount;
   uint32_t    instanceCount;
   uint32_t    firstVertex;
   uint32_t    firstInstance;
} VkDrawIndirectCommand;

typedef struct VkDrawIndexedIndirectCommand {
   uint32_t    indexCount;
   uint32_t    instanceCount;
   uint32_t    firstIndex;
   int32_t     vertexOffset;
   uint32_t    firstInstance;
} VkDrawIndexedIndirectCommand;

typedef struct VkSurfaceFormatKHR {
   VkFormat           format;
   VkColorSpaceKHR    colorSpace;
} VkSurfaceFormatKHR;

typedef struct VkSurfaceCapabilitiesKHR {
   uint32_t                         minImageCount;
   uint32_t                         maxImageCount;
   VkExtent2D                       currentExtent;
   VkExtent2D                       minImageExtent;
   VkExtent2D                       maxImageExtent;
   uint32_t                         maxImageArrayLayers;
   VkSurfaceTransformFlagsKHR       supportedTransforms;
   VkSurfaceTransformFlagBitsKHR    currentTransform;
   VkCompositeAlphaFlagsKHR         supportedCompositeAlpha;
   VkImageUsageFlags                supportedUsageFlags;
} VkSurfaceCapabilitiesKHR;

typedef struct VkPresentInfoKHR {
   VkStructureType          sType;
   const void*              pNext;
   uint32_t                 waitSemaphoreCount;
   const VkSemaphore*       pWaitSemaphores;
   uint32_t                 swapchainCount;
   const VkSwapchainKHR*    pSwapchains;
   const uint32_t*          pImageIndices;
   VkResult*                pResults;
} VkPresentInfoKHR;

typedef struct VkDeviceGroupSwapchainCreateInfoKHR {
   VkStructureType                     sType;
   const void*                         pNext;
   VkDeviceGroupPresentModeFlagsKHR    modes;
} VkDeviceGroupSwapchainCreateInfoKHR;

typedef struct VkSwapchainCreateInfoKHR {
   VkStructureType                  sType;
   const void*                      pNext;
   VkSwapchainCreateFlagsKHR        flags;
   VkSurfaceKHR                     surface;
   uint32_t                         minImageCount;
   VkFormat                         imageFormat;
   VkColorSpaceKHR                  imageColorSpace;
   VkExtent2D                       imageExtent;
   uint32_t                         imageArrayLayers;
   VkImageUsageFlags                imageUsage;
   VkSharingMode                    imageSharingMode;
   uint32_t                         queueFamilyIndexCount;
   const uint32_t*                  pQueueFamilyIndices;
   VkSurfaceTransformFlagBitsKHR    preTransform;
   VkCompositeAlphaFlagBitsKHR      compositeAlpha;
   VkPresentModeKHR                 presentMode;
   VkBool32                         clipped;
   VkSwapchainKHR                   oldSwapchain;
} VkSwapchainCreateInfoKHR;

#ifdef _WIN32
typedef VkFlags VkWin32SurfaceCreateFlagsKHR;

typedef struct VkWin32SurfaceCreateInfoKHR {
   VkStructureType                 sType;
   const void*                     pNext;
   VkWin32SurfaceCreateFlagsKHR    flags;
   struct HINSTANCE__*             hinstance;
   struct HWND__*                  hwnd;
} VkWin32SurfaceCreateInfoKHR;
#endif   //_WIN32

#ifndef NDEBUG
VK_DEFINE_NON_DISPATCHABLE_HANDLE(VkDebugUtilsMessengerEXT)

typedef enum VkObjectType {
   VK_OBJECT_TYPE_UNKNOWN = 0,
   VK_OBJECT_TYPE_INSTANCE = 1,
   VK_OBJECT_TYPE_PHYSICAL_DEVICE = 2,
   VK_OBJECT_TYPE_DEVICE = 3,
   VK_OBJECT_TYPE_QUEUE = 4,
   VK_OBJECT_TYPE_SEMAPHORE = 5,
   VK_OBJECT_TYPE_COMMAND_BUFFER = 6,
   VK_OBJECT_TYPE_FENCE = 7,
   VK_OBJECT_TYPE_DEVICE_MEMORY = 8,
   VK_OBJECT_TYPE_BUFFER = 9,
   VK_OBJECT_TYPE_IMAGE = 10,
   VK_OBJECT_TYPE_EVENT = 11,
   VK_OBJECT_TYPE_QUERY_POOL = 12,
   VK_OBJECT_TYPE_BUFFER_VIEW = 13,
   VK_OBJECT_TYPE_IMAGE_VIEW = 14,
   VK_OBJECT_TYPE_SHADER_MODULE = 15,
   VK_OBJECT_TYPE_PIPELINE_CACHE = 16,
   VK_OBJECT_TYPE_PIPELINE_LAYOUT = 17,
   VK_OBJECT_TYPE_RENDER_PASS = 18,
   VK_OBJECT_TYPE_PIPELINE = 19,
   VK_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT = 20,
   VK_OBJECT_TYPE_SAMPLER = 21,
   VK_OBJECT_TYPE_DESCRIPTOR_POOL = 22,
   VK_OBJECT_TYPE_DESCRIPTOR_SET = 23,
   VK_OBJECT_TYPE_FRAMEBUFFER = 24,
   VK_OBJECT_TYPE_COMMAND_POOL = 25,
   VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION = 1000156000,
   VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE = 1000085000,
   VK_OBJECT_TYPE_SURFACE_KHR = 1000000000,
   VK_OBJECT_TYPE_SWAPCHAIN_KHR = 1000001000,
   VK_OBJECT_TYPE_DISPLAY_KHR = 1000002000,
   VK_OBJECT_TYPE_DISPLAY_MODE_KHR = 1000002001,
   VK_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT = 1000011000,
   VK_OBJECT_TYPE_OBJECT_TABLE_NVX = 1000086000,
   VK_OBJECT_TYPE_INDIRECT_COMMANDS_LAYOUT_NVX = 1000086001,
   VK_OBJECT_TYPE_DEBUG_UTILS_MESSENGER_EXT = 1000128000,
   VK_OBJECT_TYPE_VALIDATION_CACHE_EXT = 1000160000,
   VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE_KHR = VK_OBJECT_TYPE_DESCRIPTOR_UPDATE_TEMPLATE,
   VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION_KHR = VK_OBJECT_TYPE_SAMPLER_YCBCR_CONVERSION,
} VkObjectType;

typedef VkFlags VkDebugUtilsMessengerCreateFlagsEXT;
typedef VkFlags VkDebugUtilsMessengerCallbackDataFlagsEXT;

typedef enum VkDebugUtilsMessageSeverityFlagBitsEXT {
   VK_DEBUG_UTILS_MESSAGE_SEVERITY_VERBOSE_BIT_EXT = 0x00000001,
   VK_DEBUG_UTILS_MESSAGE_SEVERITY_INFO_BIT_EXT = 0x00000010,
   VK_DEBUG_UTILS_MESSAGE_SEVERITY_WARNING_BIT_EXT = 0x00000100,
   VK_DEBUG_UTILS_MESSAGE_SEVERITY_ERROR_BIT_EXT = 0x00001000,
} VkDebugUtilsMessageSeverityFlagBitsEXT;
typedef VkFlags VkDebugUtilsMessageSeverityFlagsEXT;

typedef enum VkDebugUtilsMessageTypeFlagBitsEXT {
   VK_DEBUG_UTILS_MESSAGE_TYPE_GENERAL_BIT_EXT = 0x00000001,
   VK_DEBUG_UTILS_MESSAGE_TYPE_VALIDATION_BIT_EXT = 0x00000002,
   VK_DEBUG_UTILS_MESSAGE_TYPE_PERFORMANCE_BIT_EXT = 0x00000004,
} VkDebugUtilsMessageTypeFlagBitsEXT;
typedef VkFlags VkDebugUtilsMessageTypeFlagsEXT;

typedef struct VkDebugUtilsLabelEXT {
   VkStructureType    sType;
   const void*        pNext;
   const char*        pLabelName;
   float              color[4];
} VkDebugUtilsLabelEXT;

typedef struct VkDebugUtilsObjectNameInfoEXT {
   VkStructureType    sType;
   const void*        pNext;
   VkObjectType       objectType;
   uint64_t           objectHandle;
   const char*        pObjectName;
} VkDebugUtilsObjectNameInfoEXT;

typedef struct VkDebugUtilsObjectTagInfoEXT {
   VkStructureType    sType;
   const void*        pNext;
   VkObjectType       objectType;
   uint64_t           objectHandle;
   uint64_t           tagName;
   size_t             tagSize;
   const void*        pTag;
} VkDebugUtilsObjectTagInfoEXT;

typedef struct VkDebugUtilsMessengerCallbackDataEXT {
   VkStructureType                              sType;
   const void*                                  pNext;
   VkDebugUtilsMessengerCallbackDataFlagsEXT    flags;
   const char*                                  pMessageIdName;
   int32_t                                      messageIdNumber;
   const char*                                  pMessage;
   uint32_t                                     queueLabelCount;
   VkDebugUtilsLabelEXT*                        pQueueLabels;
   uint32_t                                     cmdBufLabelCount;
   VkDebugUtilsLabelEXT*                        pCmdBufLabels;
   uint32_t                                     objectCount;
   VkDebugUtilsObjectNameInfoEXT*               pObjects;
} VkDebugUtilsMessengerCallbackDataEXT;

typedef VkBool32(VKAPI_PTR *PFN_vkDebugUtilsMessengerCallbackEXT)(
   VkDebugUtilsMessageSeverityFlagBitsEXT           messageSeverity,
   VkDebugUtilsMessageTypeFlagsEXT                  messageType,
   const VkDebugUtilsMessengerCallbackDataEXT*      pCallbackData,
   void*                                            pUserData);

typedef struct VkDebugUtilsMessengerCreateInfoEXT {
   VkStructureType                         sType;
   const void*                             pNext;
   VkDebugUtilsMessengerCreateFlagsEXT     flags;
   VkDebugUtilsMessageSeverityFlagsEXT     messageSeverity;
   VkDebugUtilsMessageTypeFlagsEXT         messageType;
   PFN_vkDebugUtilsMessengerCallbackEXT    pfnUserCallback;
   void*                                   pUserData;
} VkDebugUtilsMessengerCreateInfoEXT;
#endif   //NDEBUG

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus
